## ---------------------------------------------------------------------------
## methods_txt.R -- writes METHODS.txt into the output directory.
##
## This replaces three files from earlier designs: metadata.rds, plan.txt and
## cell_type_summary.csv. The only machine-readable state that was genuinely
## needed is the platform, which already travels in sample_sheet.csv as
## detected_platform, plus the package and sesame versions, which ride as an
## attribute on betas_all.rds. Everything else was documentation, and prose is
## a better container for documentation than three small files nobody opens.
##
## The output is written in the register of a journal Methods section with the
## run's real numbers substituted, so that it can be pasted into a manuscript
## with light editing.
## ---------------------------------------------------------------------------

#' Write the run's Methods description
#'
#' @param dir output directory.
#' @param info a list of run facts assembled by \code{\link{qc}}.
#' @return the path written, invisibly.
#' @export
#' @examples
#' \dontrun{
#' writemethods("~/qcout", info)
#' }
writemethods <- function(dir, info) {
  p <- mqcpath(dir, "methods", create = TRUE)
  write_atomic(methodstext(info), p,
               function(o, f) writeLines(o, f))
  invisible(p)
}

#' Compose the Methods text
#'
#' @param i a list of run facts.
#' @return a character vector of lines.
#' @export
#' @examples
#' methodstext(list(platform = "EPIC", n_samples = 10L, n_probes = 866553L))
methodstext <- function(i) {
  g <- function(k, d = NA) if (is.null(i[[k]])) d else i[[k]]
  num <- function(x) if (is.null(x) || is.na(x)) "NA" else format(x, big.mark = ",")
  L <- character(0)
  add <- function(...) L <<- c(L, paste0(...))
  para <- function(...) { add(...); add("") }

  add("METHODS")
  add("========")
  add("")
  add(sprintf("Generated by methylQC %s on %s.",
              g("pkg_version", "3.0.0"), g("date", as.character(Sys.Date()))))
  add("")

  add("Samples and platform")
  add("--------------------")
  para(sprintf(
    "DNA methylation was profiled on the Illumina Infinium %s BeadChip. ",
    g("platform")),
    sprintf("Raw IDAT files for %s samples across %s batch folder(s) were read from '%s'. ",
            num(g("n_samples")), num(g("n_batches")), g("indir")),
    if (isTRUE(g("n_failed", 0) > 0))
      sprintf("%s sample(s) could not be processed and are listed in data/metadata/failed_samples.csv; they are retained in the sample sheet with missing values and are flagged. ",
              num(g("n_failed"))) else "",
    sprintf("The array carries %s probes.", num(g("n_probes"))))

  add("Signal processing")
  add("-----------------")
  para(
    "Each IDAT pair was processed independently using the sesame package ",
    sprintf("(version %s). ", g("sesame_version", "unknown")),
    "Processing proceeded in three stages so that each quantity could be ",
    "measured at the point where it is meaningful. First, Infinium type I ",
    "probe colour channels were re-inferred from the data (sesame prep code ",
    "\"C\"). Instrument diagnostics were recorded at this point, before any ",
    "correction: mean total intensity, in-band and out-of-band intensity by ",
    "colour channel, the red/green distortion ratio, probe counts by design ",
    "type, and colour channel switch counts. Out-of-band intensity is a ",
    "measurement of background, and dye bias is by definition the quantity ",
    "that dye bias correction removes, so both were measured before those ",
    "corrections were applied. Second, non-linear dye bias correction was ",
    "applied (prep code \"D\"), after which detection p-values were computed ",
    "with ELBAR. Third, noob background correction was applied (prep code ",
    "\"B\") and beta values were extracted.")
  para(
    "Detection p-values were computed once, between dye bias correction and ",
    "noob, and retained. This ordering is required: noob rewrites the four ",
    "signal columns from which the out-of-band background estimate is drawn, ",
    "so a detection calculation performed afterwards compares corrected ",
    "foreground against corrected background and does not correspond to the ",
    "mask it is meant to explain.")
  para(
    "ELBAR (ELiminate BAckground-dominated Reading) was used in preference to ",
    "pOOBAH. pOOBAH treats out-of-band signal as background by assumption; ",
    "ELBAR derives the background population empirically from the data's own ",
    "intensity profile by scanning intensity windows for the point at which ",
    "the spread of beta values begins to widen. ELBAR emits a warning when ",
    "its assumptions fail, either because the background is dichotomous or ",
    "because it lacks variation; any such warnings for this run appear in ",
    "logs/pipeline.log.")

  add("Masking")
  add("-------")
  para(
    "Beta values are stored without any mask applied. Two mask types are ",
    "stored separately alongside them. The design mask flags probes with ",
    "known design problems (multi-mapping, overlap with common SNPs, ",
    "cross-hybridisation); it is a property of the platform, identical for ",
    "every sample, and is stored once as a named logical vector ",
    sprintf("(%s of %s probes, %.1f%%). ",
            num(g("n_design_masked")), num(g("n_probes")),
            100 * (g("n_design_masked", 0) / max(1, g("n_probes", 1)))),
    "The detection mask is not stored as a mask at all: the full matrix of ",
    "ELBAR p-values is retained for every probe in every sample, so that any ",
    "threshold can be applied downstream without reprocessing. Keeping the ",
    "two separate means a probe that is masked by design can still be ",
    "recovered together with its detection status, which matters for ",
    "epigenetic clocks and other published probe sets that include ",
    "design-masked probes.")
  para(
    sprintf("Unless stated otherwise, downstream analyses used maskuse = \"%s\" ",
            g("maskuse", "both")),
    sprintf("with a detection p-value threshold of %s.", g("detp", "0.05")))

  if (isTRUE(g("collapsed", FALSE))) {
    add("EPICv2 replicate probes")
    add("-----------------------")
    para(
      "EPICv2 measures some CpG sites with more than one probe design, ",
      "distinguished by a suffix on the probe identifier. Replicate groups ",
      sprintf("were reduced to one measurement per site using the \"%s\" method. ",
              g("collapsemethod", "peters")),
      if (identical(g("collapsemethod"), "peters"))
        paste0("Under this method the probe recommended as superior by Peters ",
               "et al. (2024, BMC Genomics 25:251) is retained and the others ",
               "discarded. Those recommendations derive from cross-platform ",
               "comparison against matched EPICv1 and whole-genome bisulphite ",
               "sequencing data, and are applied here from a table frozen at ",
               "package build time so that annotation updates cannot alter ",
               "results for an existing analysis. ") else "",
      "Averaging replicates was avoided because probe design affects ",
      "hybridisation, so an average of two designs corresponds to neither. ",
      sprintf("%s probe(s) were reduced to %s sites.",
              num(g("n_probes_precollapse")), num(g("n_probes"))))
  }

  add("Quality control")
  add("---------------")
  para(
    "Per-sample call rate was computed as the fraction of all probes on the ",
    "array with a detection p-value at or below the threshold. The ",
    "denominator is every probe, so probes whose p-value could not be ",
    "computed count as failures rather than being excluded from both terms. ",
    sprintf("Samples with a call rate below %s were flagged (%s of %s samples). ",
            g("samplemin", "0.95"), num(g("n_low_callrate")), num(g("n_samples"))))
  para(
    "Low-intensity outliers were identified relative to the cohort rather ",
    "than against a fixed cutoff, because absolute intensity depends on ",
    "scanner, chemistry and DNA input. Mean intensity was log2 transformed ",
    "and samples falling more than ",
    sprintf("%s median absolute deviations below the cohort median were ",
            g("intmad", "3")),
    sprintf("flagged (%s samples; cohort median %s, cutoff %s). ",
            num(g("n_low_intensity")), g("int_median", "NA"), g("int_cutoff", "NA")),
    "A relative rule cannot detect a uniformly degraded cohort, so the ",
    sprintf("cohort median was additionally compared against an absolute floor of %s; ",
            g("intfloor", "1300")),
    if (isTRUE(g("cohort_low", FALSE)))
      "THIS RUN FELL BELOW THAT FLOOR and should be treated as degraded overall. "
    else "this run was above that floor. ")
  ## The sex paragraph must not claim a comparison that did not happen: the
  ## caller declines to split a cohort whose chrY intensity is unimodal.
  if (isTRUE(g("sex_called", FALSE))) {
    para(
      "Sex was called from sex-chromosome intensity: median total intensity ",
      "over curated chrY and X-linked probe sets was computed per sample, and ",
      "the cohort was split on log2 chrY intensity at the point of greatest ",
      "separation. The split was accepted only because the two groups were ",
      "separated by a clear band of empty space relative to within-group ",
      "spread. Samples lying far from both cluster axes are reported as ",
      sprintf("unclear rather than forced into the nearer group (%s unclear). ",
              num(g("n_sex_unclear"))),
      "Where a reported sex column was available the call was compared against ",
      sprintf("it (%s mismatch(es)). ", num(g("n_sex_mismatch"))),
      "Reported ages more than three cohort standard deviations from the mean ",
      "were recorded as outliers but were not used to exclude samples.")
  } else {
    para(
      "No sex was called. Sex calling here is cohort-relative: it splits the ",
      "cohort on chrY intensity and requires the two groups to be genuinely ",
      "separated. This cohort's chrY intensity is not bimodal -- it is ",
      "single-sex, too small, or too noisy -- so no split was accepted and no ",
      "sex mismatches are reported. A cohort-relative caller that split it ",
      "anyway would label roughly half the samples as mismatches. ",
      "Reported ages more than three cohort standard deviations from the mean ",
      "were recorded as outliers but were not used to exclude samples.")
  }

  add("Dimensionality reduction")
  add("------------------------")
  para(
    "Principal component analysis was computed on a probe set defined ",
    "without reference to any user-configurable threshold, so that it is ",
    "stable across re-runs and comparable across cohorts of different size. ",
    "Probes were restricted to cg and ch identifiers, excluding sex ",
    "chromosomes and design-masked probes, and further restricted to those ",
    "with a detection failure rate of at most 1 per cent of samples at a ",
    "fixed internal threshold of 0.05. Residual missing values were filled ",
    "with the probe mean, and the 100,000 most variable probes were retained ",
    sprintf("(%s probes entered the analysis). ", num(g("n_pca_probes"))),
    "Requiring complete data in every sample was avoided because it makes the ",
    "retained probe set shrink as the cohort grows.")

  if (isTRUE(g("cells_ok", FALSE))) {
    add("Cell composition")
    add("----------------")
    para(
      sprintf("Cell type proportions were estimated with EpiDISH using the %s ",
              g("dishref", "blood")),
      sprintf("reference panel and the %s method, over %s reference probes ",
              g("dishmethod", "RPC"), num(g("n_dish_probes"))),
      sprintf("matched on this array, yielding %s cell type(s). ",
              num(g("n_cell_types"))),
      "Estimates are assigned into the sample sheet.")
  }

  if (isTRUE(g("clock_ok", FALSE))) {
    add("Epigenetic age")
    add("--------------")
    para(
      sprintf("Epigenetic age was estimated with the %s clock, whose ",
              g("clock", "Horvath353")),
      "coefficients ship with methylQC rather than being fetched at run time, ",
      "so results are reproducible across annotation releases. ",
      "No mask was applied before prediction, because the published clocks ",
      "were fitted on unmasked beta values. ",
      sprintf("%s of the model's %s probes were present on this array; ",
              num(g("n_clock_present")), num(g("n_clock_model"))),
      "any missing probe was filled from the cohort mean for that probe, not ",
      "from a constant, and the per-sample probe count is recorded in the ",
      "sample sheet.")
  }

  add("Computation")
  add("-----------")
  para(
    sprintf("Processing used %s worker process(es) with a batch size of %s. ",
            g("workers", "1"), g("batch", "1")),
    sprintf("Stage 1 completed in %s. ", g("stage1_time", "unknown")),
    "Parallelism is by forking and is therefore available on macOS and Linux ",
    "only. Platform annotation was resolved once in the parent process and ",
    "passed explicitly to every worker, so that no worker performs its own ",
    "annotation lookup.",
    if (isTRUE(g("extreme", FALSE)))
      " Extreme memory conservation mode was used: per-batch matrices were written to disk and never assembled in memory. Use makemat() to reassemble them." else "")

  add("Outputs")
  add("-------")
  add("  METHODS.txt                          this file")
  add("  logs/pipeline.log                    full processing log")
  add("  data/matrices/betas_all.rds          beta values, unmasked, all probes")
  add("  data/matrices/detP_all.rds           ELBAR detection p-values, all probes")
  add("  data/matrices/design_mask.rds        named logical vector, platform-level")
  add("  data/matrices/snp_betas.rds          rs probe beta values")
  add("  data/metadata/sample_sheet.csv       one row per sample, all metrics and flags")
  add("  data/metadata/failed_samples.csv     samples that could not be processed")
  add("  data/metadata/failed_probes.csv      probes failing in many samples")
  add("  data/metadata/pc_scores.csv          principal component scores")
  add("  data/metadata/snp_concordance.csv    rs-probe genotype agreement by pair")
  add("  data/metadata/run_info.rds           Stage 1 run facts, read by prep()")
  add("  qc/qc_plots.pdf                      QC report")
  add("  qc/qccache.rds                       derived summaries for qcplots()")
  add("")
  add("M-values are not stored. They are a one-line transform of the beta")
  add("matrix: methylQC::mvals(betas).")
  add("")

  add("References")
  add("----------")
  add("  Zhou W, Triche TJ, Laird PW, Shen H. SeSAMe: reducing artifactual")
  add("    detection of DNA methylation by Infinium BeadChips in genomically")
  add("    heterogeneous contexts. Nucleic Acids Research 2018;46(20):e123.")
  add("  Zhou W, et al. Low-input and single-cell methods for Infinium DNA")
  add("    methylation BeadChips. Nucleic Acids Research 2024;52(7):e38.")
  add("    [ELBAR]")
  add("  Triche TJ, et al. Low-level processing of Illumina Infinium DNA")
  add("    Methylation BeadArrays. Nucleic Acids Research 2013;41(7):e90.")
  add("    [noob]")
  if (isTRUE(g("collapsed", FALSE))) {
    add("  Peters TJ, et al. Characterisation and reproducibility of the")
    add("    HumanMethylationEPIC v2.0 BeadChip for DNA methylation profiling.")
    add("    BMC Genomics 2024;25:251.")
  }
  add("")
  L
}
