## ---------------------------------------------------------------------------
## plots.R -- the QC report.
##
## Goal:    one multi-page PDF that shows, per sample, what is wrong and why.
## Approach: every per-sample panel carries the SAME flag colouring, so a
##          sample flagged on the call-rate panel is identifiable on the
##          intensity, density, sex, age, MDS and PCA panels too. Panels split
##          by whether a user-tunable threshold reaches them.
## Inputs:  the flagged metrics frame and the QC cache.
## Outputs: qc_plots.pdf, failed_probes.csv, pc_scores.csv.
## Usage:   qcreport(flags, cc, probe_fail, out, failcsv, pccsv)
##
## FROZEN VERSUS REGENERATED
## -------------------------
##   Regenerated by qcplots():  call rate, intensity, probe failure, density,
##                              sex, age, MDS, and the PC/metadata panels
##   Frozen after Stage 2:      the PCA and MDS coordinates themselves
##
## Everything except the coordinates is recomputed from qccache.rds, so a
## threshold change re-renders the whole report in about a second and never
## opens a matrix file. The coordinates are frozen legitimately rather than
## merely reused: pcainput() defines its probe set without reference to any
## user-tunable threshold, so re-running with a different `detp` could not
## change them.
## ---------------------------------------------------------------------------

## Fixed parameters of the PCA input. Deliberately NOT user options.
.MQC_PCA_NTOP   <- 100000L   # top-variance probes retained
.MQC_PCA_DETP   <- 0.05      # internal detection threshold, not cfg$detp
.MQC_PCA_TOLER  <- 0.01      # allow failure in up to 1% of samples

## Probes carried into the MDS distance, from the PCA input.
.MQC_MDS_NTOP   <- 5000L

## The PC/metadata pages. Six panels to a page, one page per variable. The
## standard variables always get a page; anything else in the sheet needs to
## reach MINETA against some PC, and MAXEXTRA caps how many such pages a wide
## sample sheet can add.
.MQC_PC_MINETA   <- 0.10
.MQC_PC_MAXEXTRA <- 6L

## Columns methylQC itself produces. Excluded from the PC/metadata panel so a
## component cannot be "explained" by a flag derived from the same matrix.
.MQC_DERIVED_COLS <- c(
  "sample_id", "Basename", "sentrix", "flagcat", "flag_reason", "flagged",
  "low_callrate", "low_intensity", "sex_mismatch", "sex_unknown",
  "sex_unclear", "mds_outlier", "age_outlier", "inferred_sex",
  "call_rate", "detp_threshold", "intensity_cutoff", "reported_age",
  "sex_confidence", "sex_chrX_intensity", "sex_chrY_intensity",
  "mean_intensity_raw", "mean_intensity_mu", "detected_platform")

## Chip position, parsed by discover() from the Sentrix barcode. Kept as
## candidates for the PC panels: slide, row and column are the physical
## variables most likely to carry a batch effect.
.MQC_POSITION_COLS <- c("sentrix_slide", "sentrix_row", "sentrix_col")

## One palette, used by every per-sample panel. The levels are fixed a priori
## and every scale is drawn with drop = FALSE, so all four appear in the legend
## of every panel whether or not the cohort contains any -- an absent category
## and an unflagged cohort would otherwise look identical.
.MQC_FLAG_COLS <- c(
  "OK"            = "steelblue",
  "Low detection" = "red3",
  "Low intensity" = "goldenrod3",
  "MDS outlier"   = "purple3")

#' Categorise each sample for colouring
#'
#' One sample can trip several flags, so the categories are ordered by
#' precedence: MDS outlier beats low intensity, which beats low detection. The
#' factor always carries all four levels.
#'
#' @param qc flagged metrics frame.
#' @return a factor with the levels of \code{.MQC_FLAG_COLS}.
#' @keywords internal
#' @noRd
.flagcat <- function(qc) {
  v <- ifelse(isTRUE_vec(qc$mds_outlier), "MDS outlier",
       ifelse(isTRUE_vec(qc$low_intensity), "Low intensity",
       ifelse(isTRUE_vec(qc$low_callrate), "Low detection", "OK")))
  factor(v, levels = names(.MQC_FLAG_COLS))
}

## NA-safe logical coercion; a flag that could not be computed is not a flag.
#' @keywords internal
#' @noRd
isTRUE_vec <- function(x) {
  if (is.null(x)) return(logical(0))
  x <- as.logical(x)
  x[is.na(x)] <- FALSE
  x
}

## limits= as well as drop=FALSE. drop=FALSE alone is enough in ggplot2 4.x,
## but naming the limits makes the guarantee explicit and independent of how a
## future ggplot2 treats unused factor levels.
.scale_flag <- function(name = NULL)
  ggplot2::scale_colour_manual(values = .MQC_FLAG_COLS, name = name,
                               drop = FALSE, limits = names(.MQC_FLAG_COLS),
                               na.value = "grey80")

.scale_flag_fill <- function(name = NULL)
  ggplot2::scale_fill_manual(values = .MQC_FLAG_COLS, name = name,
                             drop = FALSE, limits = names(.MQC_FLAG_COLS),
                             na.value = "grey80")

#' Build the PCA input matrix
#'
#' Selection criteria are fixed and independent of the user's options, so that
#' the PCA is stable across re-runs and comparable across cohorts of different
#' size.
#'
#' @param betas unmasked beta matrix.
#' @param detp detection p-value matrix.
#' @param design named logical design mask.
#' @param sex_probes probe IDs on the sex chromosomes.
#' @param logger optional logger.
#' @return a numeric matrix of probes by samples, free of \code{NA}.
#' @export
#' @examples
#' \dontrun{
#' bt <- pcainput(betas, detp, design, sexprobes("EPIC"))
#' }
pcainput <- function(betas, detp = NULL, design = NULL, sex_probes = character(0),
                     logger = NULL) {
  logger <- logger %||% nulllog()

  keep <- grepl("^(cg|ch)", rownames(betas))
  if (length(sex_probes)) keep <- keep & !(rownames(betas) %in% sex_probes)
  if (!is.null(design)) {
    dm <- align_to(design, rownames(betas), "design mask", fill = TRUE)
    keep <- keep & !dm
  }
  b <- betas[keep, , drop = FALSE]
  if (!nrow(b)) return(b)

  if (!is.null(detp)) {
    d <- conform_to(detp, betas, "detP matrix")[keep, , drop = FALSE]

    ## Samples that failed outright are excluded from the denominator. One
    ## dead array makes every probe's failure rate at least 1/n, which at the
    ## fixed 1% tolerance discarded the ENTIRE probe set and silently dropped
    ## the PCA, MDS and scree panels from the report.
    dead <- colMeans(is.na(d) | d > .MQC_PCA_DETP) > 0.5
    if (any(dead) && sum(!dead) >= 3L) {
      logger$log("pca", sprintf(
        "%d sample(s) failed detection almost everywhere and are excluded from the probe-selection denominator",
        sum(dead)))
      d <- d[, !dead, drop = FALSE]
    }

    fail <- rowMeans(is.na(d) | d > .MQC_PCA_DETP)
    b <- b[fail <= .MQC_PCA_TOLER, , drop = FALSE]
  }
  if (!nrow(b)) return(b)

  ## Fill the residual handful of NAs with the probe mean. At <= 1% missing
  ## this is negligible, and it removes the complete.cases fragility.
  na_idx <- which(is.na(b), arr.ind = TRUE)
  if (nrow(na_idx)) {
    rm_ <- rowMeans(b, na.rm = TRUE)
    b[na_idx] <- rm_[na_idx[, 1]]
    b <- b[is.finite(rowMeans(b)), , drop = FALSE]
  }

  v <- .rowVars(b)
  top <- order(v, decreasing = TRUE)[seq_len(min(.MQC_PCA_NTOP, length(v)))]
  out <- b[sort(top), , drop = FALSE]
  logger$log("pca", sprintf(
    "PCA input: %s probes (cg/ch, sex and design excluded, detection failure <= %.0f%%)",
    format(nrow(out), big.mark = ","), 100 * .MQC_PCA_TOLER))
  out
}

## The sentence that describes what pcainput() kept, reused by both the MDS and
## the PCA panels so the reader never has to guess what "retained" means.
.retained_text <- function(n_probes = NA) {
  sprintf(paste("Retained probes = cg/ch probes only, excluding sex chromosomes",
                "and design-masked probes, and requiring detection failure in",
                "at most %.0f%% of samples at a fixed internal p of %.2f;",
                "residual gaps filled with the probe mean, then the %s most",
                "variable kept%s."),
          100 * .MQC_PCA_TOLER, .MQC_PCA_DETP,
          format(.MQC_PCA_NTOP, big.mark = ","),
          if (is.na(n_probes)) "" else
            sprintf(" (%s entered)", format(n_probes, big.mark = ",")))
}

#' Compute the frozen PCA
#'
#' @param bt output of \code{\link{pcainput}}.
#' @param logger optional logger.
#' @return a list with \code{scores}, \code{sdev} and \code{n_probes}, or
#'   \code{NULL} when there is too little data.
#' @export
#' @examples
#' \dontrun{
#' pc <- runpca(pcainput(betas, detp, design))
#' }
runpca <- function(bt, logger = NULL) {
  logger <- logger %||% nulllog()
  if (is.null(bt) || nrow(bt) < 100L || ncol(bt) < 3L) {
    logger$log("pca", "too few probes or samples for PCA")
    return(NULL)
  }
  t0 <- Sys.time()
  ## Centred but NOT scaled. Betas already share one bounded scale, so dividing
  ## each probe by its own SD gives every probe equal weight and exactly undoes
  ## the top-variance selection pcainput() just performed; it also divides
  ## near-constant probes by floating-point residue.
  p <- stats::prcomp(t(bt), center = TRUE, scale. = FALSE)
  logger$log("pca", sprintf("PCA on %s probes x %d samples in %s",
                            format(nrow(bt), big.mark = ","), ncol(bt),
                            fmtdur(as.numeric(difftime(Sys.time(), t0, units = "secs")))))
  ## `rotation` is n_probes x n_PCs and is never used by the plots; dropping
  ## it turns a 1.2 GiB object into a few megabytes.
  list(scores = p$x, sdev = p$sdev, n_probes = nrow(bt))
}

#' Multidimensional scaling coordinates
#'
#' @param bt PCA input matrix.
#' @param logger optional logger.
#' @return a two-column matrix, or \code{NULL}.
#' @keywords internal
#' @noRd
runmds <- function(bt, logger = NULL) {
  logger <- logger %||% nulllog()
  if (is.null(bt) || ncol(bt) < 3L || !nrow(bt)) return(NULL)
  ## pcainput() returns its probes in row order, not variance order, so taking
  ## the first rows sampled one end of the manifest rather than the most
  ## informative probes. Take the most variable instead.
  n <- min(.MQC_MDS_NTOP, nrow(bt))
  sub <- if (n < nrow(bt)) {
    v <- .rowVars(bt)
    bt[sort(order(v, decreasing = TRUE)[seq_len(n)]), , drop = FALSE]
  } else bt
  d <- tryCatch(stats::dist(t(sub)), error = function(e) NULL)
  if (is.null(d)) return(NULL)
  m <- tryCatch(stats::cmdscale(d, k = 2), error = function(e) NULL)
  if (is.null(m) || !is.matrix(m) || ncol(m) < 2L) return(NULL)
  colnames(m) <- c("MDS1", "MDS2")
  attr(m, "n_probes") <- n
  m
}

#' Flag samples far from the cohort centroid in MDS space
#'
#' Distance is measured from the coordinate-wise median, which is unaffected by
#' the outliers it is meant to find, and scaled by the median absolute
#' deviation of those distances.
#'
#' @param mds a two-column MDS coordinate matrix.
#' @param nsd distance, in SDs, beyond which a sample is an outlier.
#' @return a named logical vector, with the radius as an attribute.
#' @export
#' @examples
#' m <- cbind(MDS1 = c(0, 0.1, -0.1, 5), MDS2 = c(0, -0.1, 0.1, 5))
#' rownames(m) <- paste0("s", 1:4)
#' mdsoutlier(m)
mdsoutlier <- function(mds, nsd = NULL) {
  nsd <- .opt(nsd, "mdssd")
  if (is.null(mds) || !is.matrix(mds) || nrow(mds) < 4L) return(NULL)
  centre <- apply(mds, 2L, stats::median, na.rm = TRUE)
  d <- sqrt(rowSums(sweep(mds, 2L, centre)^2))
  s <- stats::mad(d)
  if (!is.finite(s) || s <= 0) s <- stats::sd(d)
  if (!is.finite(s) || s <= 0) return(NULL)
  r <- stats::median(d) + nsd * s
  out <- stats::setNames(d > r, rownames(mds))
  attr(out, "radius") <- r
  attr(out, "centre") <- centre
  attr(out, "dist") <- d
  out
}

#' Per-sample beta density curves
#'
#' Cached rather than recomputed, because the density of a beta matrix does
#' not depend on any threshold.
#'
#' @param betas beta matrix.
#' @param nsub probes sampled per column.
#' @return a list with \code{x} and \code{y}.
#' @keywords internal
#' @noRd
betadensity <- function(betas, nsub = 20000L) {
  if (is.null(betas) || !ncol(betas)) return(NULL)
  ## Reproducible without stealing the caller's random stream: save and restore
  ## .Random.seed around the draw.
  old <- if (exists(".Random.seed", envir = globalenv(), inherits = FALSE))
    get(".Random.seed", envir = globalenv()) else NULL
  on.exit({
    if (is.null(old)) suppressWarnings(rm(".Random.seed", envir = globalenv()))
    else assign(".Random.seed", old, envir = globalenv())
  }, add = TRUE)
  set.seed(1L)
  idx <- if (nrow(betas) > nsub) sample.int(nrow(betas), nsub) else seq_len(nrow(betas))
  gx <- seq(0, 1, length.out = 512L)
  ys <- vapply(seq_len(ncol(betas)), function(j) {
    v <- betas[idx, j]; v <- v[is.finite(v)]
    if (length(v) < 100L) return(rep(NA_real_, length(gx)))
    stats::density(v, from = 0, to = 1, n = length(gx))$y
  }, numeric(length(gx)))
  colnames(ys) <- colnames(betas)
  list(x = gx, y = ys)
}


## ---------------------------------------------------------------------------
## The report
## ---------------------------------------------------------------------------

.theme_qc <- function() {
  ggplot2::theme_minimal(base_size = 10) +
    ggplot2::theme(
      panel.grid.minor = ggplot2::element_blank(),
      plot.title = ggplot2::element_text(face = "bold", size = 11),
      plot.subtitle = ggplot2::element_text(size = 9, colour = "grey30"),
      legend.background = ggplot2::element_rect(fill = "white",
                                                colour = "grey70",
                                                linewidth = 0.3),
      legend.key = ggplot2::element_blank(),
      legend.margin = ggplot2::margin(4, 6, 4, 6))
}

#' Render the QC report
#'
#' @param qc per-sample metrics, already flagged.
#' @param cc the QC cache.
#' @param probe_fail named numeric vector of per-probe failure rates.
#' @param out destination PDF path.
#' @param failcsv destination for the failing-probe list.
#' @param pccsv destination for PC scores.
#' @param cfg options list.
#' @param logger optional logger.
#' @return \code{out}, invisibly.
#' @export
#' @examples
#' \dontrun{
#' qcreport(qc, cc, probe_fail, "qc_plots.pdf", "failed_probes.csv", "pc.csv")
#' }
qcreport <- function(qc, cc, probe_fail, out, failcsv, pccsv,
                     cfg = NULL, logger = NULL) {
  logger <- logger %||% nulllog()
  cfg <- cfg %||% mqcopts()
  th <- .theme_qc()
  qc$flagcat <- .flagcat(qc)

  dir.create(dirname(out), recursive = TRUE, showWarnings = FALSE)
  grDevices::pdf(out, width = 9, height = 6.5, onefile = TRUE)
  on.exit(grDevices::dev.off(), add = TRUE)

  .p_callrate(qc, cfg, th)
  .p_intensity(qc, cfg, th)
  .p_probefail(probe_fail, cc, cfg, th, failcsv, logger)
  .p_density(cc, qc, th)
  .p_cells(qc, th)
  .p_sex(qc, cc, th)
  .p_age(qc, th)
  .p_mds(cc, qc, cfg, th)
  .p_pca(cc, qc, th, pccsv, logger)
  .p_pcvars(cc, qc, th, logger)

  logger$log("plots", sprintf("QC report written to %s", out))
  invisible(out)
}

## The v2 report's three sample-level panels, restored on request. They use the
## v2 colour scheme (steelblue / red3 / goldenrod3) rather than the shared flag
## palette the later panels carry, because that is what the v2 report looked
## like and matching it was the point.

## Above this many samples the per-sample bar labels stop being legible and are
## dropped; the bars themselves still show the distribution.
.MQC_BAR_MAXLAB <- 120L

.p_callrate <- function(qc, cfg, th) {
  d <- qc
  d$status <- .flagcat(d)
  lab <- nrow(d) <= .MQC_BAR_MAXLAB
  thd <- th + ggplot2::theme(
    axis.text.y = if (lab) ggplot2::element_text(size = 7)
                  else ggplot2::element_blank())

  print(ggplot2::ggplot(d, ggplot2::aes(
        x = stats::reorder(.data$sample_id, .data$call_rate),
        y = .data$call_rate, fill = .data$status)) +
    ggplot2::geom_col() +
    .scale_flag_fill() +
    ggplot2::geom_hline(yintercept = cfg$samplemin, linetype = "dashed",
                        colour = "black", linewidth = 0.7) +
    ggplot2::coord_flip() + thd +
    ggplot2::labs(
      title = "Detection rate per sample (frac_dt)",
      subtitle = sprintf(
        "All %d samples; red = below %.2f threshold; dashed line = threshold.%s Detection threshold %.4g.",
        nrow(d), cfg$samplemin,
        if (lab) "" else sprintf(" Sample labels omitted above %d samples.",
                                 .MQC_BAR_MAXLAB),
        cfg$detp),
      x = NULL, y = "Fraction detected"))
}

## Retained as the documented name for the precedence rule; identical to
## .flagcat(), which every other panel uses.
#' @keywords internal
#' @noRd
.intensity_fillcat <- function(qc) .flagcat(qc)

## Histogram of mean intensity, filled by flag with a fixed precedence.
.p_intensity <- function(qc, cfg, th) {
  d <- qc
  d$fillcat <- .intensity_fillcat(d)
  cut <- unique(stats::na.omit(d$intensity_cutoff))[1]

  p <- ggplot2::ggplot(d, ggplot2::aes(.data$mean_intensity_raw,
                                       fill = .data$fillcat)) +
    ggplot2::geom_histogram(bins = 30, alpha = 0.85, position = "identity") +
    .scale_flag_fill() + th +
    ggplot2::labs(
      title = "Mean intensity per sample",
      subtitle = sprintf(
        paste("All %d samples; colour precedence MDS outlier > low intensity >",
              "low detection. Dashed line is the %g-MAD cut-off below the",
              "cohort median of log2 intensity."), nrow(d), cfg$intmad),
      x = "Mean intensity", y = "Count")
  if (length(cut) && is.finite(cut))
    p <- p + ggplot2::geom_vline(xintercept = cut, linetype = "dashed",
                                 colour = "black", linewidth = 0.7)
  print(p)
}

## Per-PROBE failure histogram over the full 0-1 range, with the y axis capped
## so the leftmost spike -- the probes that pass in essentially every sample --
## does not flatten everything else into the axis.
## The y cap deliberately ignores the leftmost spike: 1.5x the tallest bar at
## fail_rate >= 0.05. Nearly every probe passes in nearly every sample, so that
## first bar is one or two orders of magnitude taller than the rest and, left
## uncapped, compresses the entire informative tail onto the axis. This 0.05 is
## about where the spike ends; it is NOT failmin, and stays put if failmin
## moves -- the two coinciding at the default is a coincidence.
#' @keywords internal
#' @noRd
.probefail_ycap <- function(counts, mids) {
  rest <- counts[mids >= 0.05]
  ycap <- if (length(rest) && max(rest) > 0) 1.5 * max(rest) else max(counts)
  if (!is.finite(ycap) || ycap <= 0) ycap <- max(counts, 1)
  ycap
}

.p_probefail <- function(pf, cc, cfg, th, failcsv, logger) {
  if (is.null(pf) || !length(pf)) return(invisible(NULL))

  keep <- rep(TRUE, length(pf))
  qnote <- " (incl. quality-masked)"
  if (!isTRUE(cfg$inclqual) && !is.null(cc$design)) {
    dm <- align_to(cc$design, names(pf), "design mask", fill = FALSE)
    dm[is.na(dm)] <- FALSE
    keep <- !dm
    qnote <- ""
    logger$log("plots", sprintf(
      "probe failure: excluding %s quality-masked probe(s)",
      format(sum(dm), big.mark = ",")))
  }
  fr <- pf[keep]
  n_total <- length(fr)
  tail_ids <- names(fr)[fr >= cfg$failmin]

  write_csv_atomic(
    data.frame(probe_id = tail_ids, fail_rate = unname(fr[tail_ids]),
               stringsAsFactors = FALSE)[order(-unname(fr[tail_ids])), ,
                                         drop = FALSE], failcsv)
  logger$log("plots", sprintf(
    "%s probe(s) of %s at or above failmin %.3f written to %s",
    format(length(tail_ids), big.mark = ","), format(n_total, big.mark = ","),
    cfg$failmin, failcsv))

  ## Bin by hand so the cap can be derived from the counts.
  nbins <- 40L
  breaks <- seq(0, 1, length.out = nbins + 1L)
  hh <- graphics::hist(fr, breaks = breaks, plot = FALSE)
  counts <- hh$counts; mids <- hh$mids

  ycap <- .probefail_ycap(counts, mids)
  clipped <- counts[1] > ycap

  print(ggplot2::ggplot(data.frame(fr = fr), ggplot2::aes(.data$fr)) +
    ggplot2::geom_histogram(breaks = breaks, fill = "steelblue",
                            colour = "white") +
    ggplot2::geom_vline(xintercept = cfg$failmin, linetype = "dashed",
                        colour = "red3", linewidth = 0.7) +
    ggplot2::annotate("text", x = cfg$failmin, y = ycap,
                      label = sprintf(" failmin = %.2f", cfg$failmin),
                      hjust = 0, vjust = 1.1, colour = "red3", size = 4) +
    ggplot2::scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.1)) +
    ggplot2::coord_cartesian(ylim = c(0, ycap)) + th +
    ggplot2::labs(
      title = "Per-probe sample-failure rate",
      subtitle = sprintf(
        "%s probes from detP%s. %s with fail >= %.2f written to %s.%s",
        format(n_total, big.mark = ","), qnote,
        format(length(tail_ids), big.mark = ","), cfg$failmin,
        basename(failcsv),
        if (clipped) sprintf(
          "\nLeftmost bar clipped: %s probes at fail_rate ~ 0 (y capped at %s).",
          format(counts[1], big.mark = ","), format(round(ycap), big.mark = ","))
        else ""),
      x = sprintf("Fraction of samples where probe failed (detP > %.2f)",
                  cfg$detp),
      y = "Number of probes"))
  invisible(NULL)
}

## Stacked composition per sample, samples ordered by similarity so that
## compositionally alike samples sit together and a departure reads as a break
## in the stack. The ordering comes from a hierarchical clustering of the
## composition matrix, but the dendrogram itself is not drawn -- it would take
## a third of the page to say what the ordering already says.
.p_cells <- function(qc, th) {
  cols <- grep("^cell_", names(qc), value = TRUE)
  cols <- cols[vapply(cols, function(k) is.numeric(qc[[k]]), logical(1))]
  if (length(cols) < 2L) return(invisible(NULL))

  m <- as.matrix(qc[, cols, drop = FALSE])
  keep <- stats::complete.cases(m)
  if (!any(keep)) return(invisible(NULL))
  m <- m[keep, , drop = FALSE]
  ids <- as.character(qc$sample_id[keep])
  types <- sub("^cell_", "", cols)

  ## Row sums are reported rather than forced to 1: EpiDISH's RPC does not
  ## constrain them, and a row summing to well under 1 means the reference
  ## panel did not explain that sample.
  rs <- rowSums(m)

  ord <- .cluster_order(m)
  ids <- ids[ord]
  m <- m[ord, , drop = FALSE]

  d <- data.frame(
    sample = factor(rep(ids, times = length(types)), levels = ids),
    type = factor(rep(types, each = length(ids)), levels = types),
    prop = as.vector(m),
    stringsAsFactors = FALSE)

  ## A fixed, reproducible qualitative palette: the same cell type gets the
  ## same colour in every report.
  pal <- stats::setNames(
    grDevices::hcl.colors(length(types), palette = "Dark 3"), types)
  ## Shrink the sample labels as the cohort grows; past a few hundred they
  ## cannot be rendered legibly at any size and are dropped.
  n <- length(ids)
  lab <- n <= 300L
  sz <- if (n <= 60L) 5.5 else if (n <= 150L) 4 else 2.6

  print(ggplot2::ggplot(d, ggplot2::aes(.data$sample, .data$prop,
                                        fill = .data$type)) +
    ggplot2::geom_col(width = 1) +
    ggplot2::scale_fill_manual(values = pal, name = NULL) +
    ggplot2::scale_y_continuous(expand = c(0, 0)) + th +
    ggplot2::theme(
      axis.text.x = if (lab)
        ggplot2::element_text(angle = 90, hjust = 1, vjust = 0.5, size = sz)
        else ggplot2::element_blank(),
      axis.ticks.x = ggplot2::element_blank(),
      panel.grid.major.x = ggplot2::element_blank()) +
    ggplot2::labs(
      title = "EpiDISH cell-type proportions",
      subtitle = sprintf(
        "%d samples; %d cell types; ordered by compositional similarity. Row-sum median=%.3f (range %.3f-%.3f).%s",
        n, length(types), stats::median(rs), min(rs), max(rs),
        if (lab) "" else " Sample labels omitted above 300 samples."),
      x = "Sample", y = "Proportion"))
}

#' Order rows by hierarchical clustering, without drawing the dendrogram
#'
#' Average linkage on Euclidean distance. Falls back to the original order when
#' there are too few rows to cluster or the distances are degenerate.
#'
#' @param m a numeric matrix, one row per sample.
#' @return an integer ordering of the rows.
#' @keywords internal
#' @noRd
.cluster_order <- function(m) {
  n <- nrow(m)
  if (n < 3L) return(seq_len(n))
  d <- tryCatch(stats::dist(m), error = function(e) NULL)
  if (is.null(d) || !all(is.finite(d)) || max(d) <= 0) return(seq_len(n))
  hc <- tryCatch(stats::hclust(d, method = "average"), error = function(e) NULL)
  if (is.null(hc)) return(seq_len(n))
  hc$order
}

.p_density <- function(cc, qc, th) {
  d <- cc$density
  if (is.null(d)) return(invisible(NULL))
  n <- ncol(d$y)
  cat_by_id <- stats::setNames(as.character(qc$flagcat), qc$sample_id)
  df <- data.frame(
    x = rep(d$x, n),
    y = as.vector(d$y),
    s = rep(colnames(d$y), each = length(d$x)),
    stringsAsFactors = FALSE)
  df$flagcat <- factor(unname(cat_by_id[df$s]), levels = names(.MQC_FLAG_COLS))
  df$flagcat[is.na(df$flagcat)] <- "OK"
  df <- df[is.finite(df$y), , drop = FALSE]
  ## Flagged curves drawn last and opaque so they are visible over the cohort.
  df$flagged <- df$flagcat != "OK"
  df <- df[order(df$flagged), , drop = FALSE]
  nflag <- length(unique(df$s[df$flagged]))
  print(ggplot2::ggplot(df, ggplot2::aes(.data$x, .data$y, group = .data$s,
                                         colour = .data$flagcat)) +
    ggplot2::geom_line(ggplot2::aes(alpha = .data$flagged), linewidth = 0.4) +
    .scale_flag() +
    ggplot2::scale_alpha_manual(values = c(`FALSE` = min(1, 15 / max(1, n)),
                                           `TRUE` = 1), guide = "none") + th +
    ggplot2::labs(
      title = "Beta value density by sample",
      subtitle = sprintf("%d samples, %d flagged. Healthy arrays are bimodal with peaks near 0 and 1; a collapsed middle peak suggests a failed array.",
                         n, nflag),
      x = "beta", y = "density"))
}

## chrX against chrY, coloured by reported sex, with the cut-off drawn. No
## subtitle: the method belongs in METHODS.md, not on the plot.
.p_sex <- function(qc, cc, th) {
  has_int <- all(c("sex_chrX_intensity", "sex_chrY_intensity") %in% names(qc)) &&
    any(is.finite(qc$sex_chrX_intensity) & is.finite(qc$sex_chrY_intensity))
  if (!has_int) return(invisible(NULL))

  d <- qc[is.finite(qc$sex_chrX_intensity) & is.finite(qc$sex_chrY_intensity), ,
          drop = FALSE]
  if (!nrow(d)) return(invisible(NULL))
  d$reported <- factor(ifelse(is.na(d$reported_sex), "not reported", d$reported_sex),
                       levels = c("F", "M", "not reported"))
  cut <- attr(cc, "sex_threshold") %||% cc$sex_threshold

  p <- ggplot2::ggplot(d, ggplot2::aes(.data$sex_chrX_intensity,
                                       .data$sex_chrY_intensity)) +
    ggplot2::geom_point(ggplot2::aes(colour = .data$reported), size = 2.2) +
    ggplot2::scale_colour_manual(
      values = c(F = "#C0392B", M = "#2E70B8", `not reported` = "grey60"),
      name = "reported sex", drop = FALSE,
      limits = c("F", "M", "not reported"))
  if (!is.null(cut) && is.finite(cut))
    p <- p + ggplot2::geom_hline(yintercept = cut, linetype = "dashed",
                                 colour = "grey25")

  print(p + th + ggplot2::labs(
    title = "Sex chromosome intensity",
    x = "median chrX (X-linked) intensity",
    y = "median chrY intensity"))
}

## Reported against predicted age, with a transparent +/- 3 SD band around the
## fitted line.
.p_age <- function(qc, th, nsd = 3) {
  ## Select the predicted-age column by type, not by prefix. flagsamples()
  ## creates `age_outlier`, a logical, and adds it BEFORE predictages() assigns
  ## `age_horvath353`, so a bare grep("^age_") picked the flag first and the
  ## panel plotted TRUE/FALSE on the y axis instead of an age.
  agecol <- grep("^age_", names(qc), value = TRUE)
  agecol <- setdiff(agecol, grep("nprobes|nmodel|outlier", agecol, value = TRUE))
  agecol <- agecol[vapply(agecol, function(k) is.numeric(qc[[k]]), logical(1))]
  if (!length(agecol) || !"reported_age" %in% names(qc) ||
      all(is.na(qc$reported_age))) return(invisible(NULL))
  ac <- agecol[1]
  d <- qc[is.finite(qc$reported_age) & is.finite(qc[[ac]]), , drop = FALSE]
  if (nrow(d) < 3L) return(invisible(NULL))
  d$pred <- d[[ac]]

  r <- suppressWarnings(stats::cor(d$reported_age, d$pred, use = "complete.obs"))
  fit <- stats::lm(pred ~ reported_age, data = d)
  s <- stats::sd(stats::residuals(fit))
  gx <- seq(min(d$reported_age), max(d$reported_age), length.out = 100)
  band <- data.frame(reported_age = gx,
                     fit = stats::predict(fit, data.frame(reported_age = gx)))
  band$lo <- band$fit - nsd * s
  band$hi <- band$fit + nsd * s
  outside <- sum(abs(stats::residuals(fit)) > nsd * s)

  print(ggplot2::ggplot(d, ggplot2::aes(.data$reported_age, .data$pred)) +
    ggplot2::geom_ribbon(data = band,
                         ggplot2::aes(x = .data$reported_age, ymin = .data$lo,
                                      ymax = .data$hi),
                         inherit.aes = FALSE, fill = "steelblue", alpha = 0.15) +
    ggplot2::geom_line(data = band,
                       ggplot2::aes(.data$reported_age, .data$fit),
                       inherit.aes = FALSE, colour = "steelblue") +
    ggplot2::geom_abline(slope = 1, intercept = 0, colour = "grey75",
                         linetype = "dotted") +
    ggplot2::geom_point(ggplot2::aes(colour = .data$flagcat), size = 1.8) +
    .scale_flag() + th +
    ggplot2::labs(
      title = "Reported age versus epigenetic age",
      subtitle = sprintf(
        "n = %d, Pearson r = %.3f. Band is +/- %g SD of the residuals about the fitted line (%d sample(s) outside); dotted line is y = x. No mask is applied before prediction.",
        nrow(d), r, nsd, outside),
      x = "reported age (years)", y = ac))
}

.p_mds <- function(cc, qc, cfg, th) {
  m <- cc$mds
  if (is.null(m)) return(invisible(NULL))
  d <- as.data.frame(m); d$sample_id <- rownames(m)
  i <- match(d$sample_id, qc$sample_id)
  d$flagcat <- qc$flagcat[i]
  d$flagcat[is.na(d$flagcat)] <- "OK"

  o <- mdsoutlier(m, cfg$mdssd)
  ring <- NULL
  if (!is.null(o)) {
    ctr <- attr(o, "centre"); rad <- attr(o, "radius")
    ang <- seq(0, 2 * pi, length.out = 200)
    ring <- data.frame(x = ctr[1] + rad * cos(ang), y = ctr[2] + rad * sin(ang))
  }

  p <- ggplot2::ggplot(d, ggplot2::aes(.data$MDS1, .data$MDS2))
  if (!is.null(ring))
    p <- p + ggplot2::geom_path(data = ring,
                                ggplot2::aes(.data$x, .data$y),
                                inherit.aes = FALSE, colour = "firebrick",
                                linetype = "dashed", linewidth = 0.4)
  print(p +
    ggplot2::geom_point(ggplot2::aes(colour = .data$flagcat), size = 1.8) +
    .scale_flag() + th +
    ggplot2::labs(
      title = "MDS of retained probes",
      subtitle = paste0(
        .retained_text(attr(m, "n_probes")), " ",
        if (is.null(o)) "" else sprintf(
          "Dashed circle is %g SD from the cohort centroid; %d sample(s) outside it.",
          cfg$mdssd, sum(o)))))
}

.p_pca <- function(cc, qc, th, pccsv, logger) {
  pc <- cc$pca
  if (is.null(pc) || is.null(pc$scores)) return(invisible(NULL))
  sc <- as.data.frame(pc$scores)
  sc$sample_id <- rownames(pc$scores)
  write_csv_atomic(sc, pccsv)

  ve <- (pc$sdev^2 / sum(pc$sdev^2)) * 100
  ns <- min(20L, length(ve))
  print(ggplot2::ggplot(
      data.frame(PC = factor(paste0("PC", seq_len(ns)),
                             levels = paste0("PC", seq_len(ns))),
                 v = ve[seq_len(ns)]),
      ggplot2::aes(.data$PC, .data$v)) +
    ggplot2::geom_col(fill = "steelblue") + th +
    ggplot2::labs(
      title = "Scree plot",
      subtitle = sprintf("Top %d of %d PCs, %d samples. %s",
                         ns, length(ve), nrow(sc), .retained_text(pc$n_probes)),
      x = NULL, y = "% variance explained"))
  logger$log("plots", sprintf("PC scores written to %s", pccsv))
}

#' Association between each PC and each categorical variable
#'
#' Eta squared from a one-way analysis of variance: the share of that PC's
#' variance explained by the grouping. Continuous variables are skipped, since
#' the point of the panel is to see which discrete factor a component tracks.
#'
#' @param scores PC score matrix.
#' @param meta data.frame of candidate variables, aligned to \code{scores}.
#' @param npc how many PCs to consider.
#' @return a data.frame of PC, variable, eta2 and p, best variable first.
#' @keywords internal
#' @noRd
.pcassoc <- function(scores, meta, npc = 6L) {
  npc <- min(npc, ncol(scores))
  usable <- vapply(meta, function(v) {
    v <- v[!is.na(v)]
    if (!length(v)) return(FALSE)
    if (is.numeric(v) && length(unique(v)) > 12L) return(FALSE)  # continuous
    nu <- length(unique(v))
    nu >= 2L && nu <= 12L && nu < length(v)
  }, logical(1))
  meta <- meta[, usable, drop = FALSE]
  if (!ncol(meta)) return(NULL)

  rows <- list()
  for (i in seq_len(npc)) {
    y <- scores[, i]
    for (k in names(meta)) {
      g <- factor(as.character(meta[[k]]))
      ok <- !is.na(y) & !is.na(g)
      if (sum(ok) < 4L || length(unique(g[ok])) < 2L) next
      f <- tryCatch(stats::aov(y[ok] ~ g[ok]), error = function(e) NULL)
      if (is.null(f)) next
      ss <- summary(f)[[1]][["Sum Sq"]]
      if (length(ss) < 2L || sum(ss) <= 0) next
      p <- tryCatch(summary(f)[[1]][["Pr(>F)"]][1], error = function(e) NA_real_)
      rows[[length(rows) + 1L]] <- data.frame(
        pc = i, variable = k, eta2 = ss[1] / sum(ss), p = p,
        stringsAsFactors = FALSE)
    }
  }
  if (!length(rows)) return(NULL)
  out <- do.call(rbind, rows)
  out[order(out$pc, -out$eta2), , drop = FALSE]
}

## ---------------------------------------------------------------------------
## PC versus metadata
##
## Six panels to a page, one page per variable, PC1 through PC6 down the page.
## A fixed set of variables is ALWAYS tested whether or not it associates with
## anything -- chip slide, chip row and column, plate, well row and column, age
## and sex -- because "this component is not the plate" is as useful to see as
## the converse, and an absent page is indistinguishable from a page that was
## never drawn.
## ---------------------------------------------------------------------------

## PCs carried into the metadata pages.
.MQC_PC_NPC <- 6L

#' The variables that always get a page
#'
#' Chip position comes from the Sentrix barcode (parsed by \code{discover()});
#' plate position comes from a well column if the sheet has one. Row and column
#' are offered for both, since a cohort can be laid out on chips, on plates, or
#' on both, and either layout can carry a batch effect.
#'
#' @param qc the flagged metrics frame, joined to the sample sheet.
#' @return a named list of vectors; absent variables are dropped.
#' @keywords internal
#' @noRd
.pc_required_vars <- function(qc) {
  cfg <- mqcopts()
  col <- function(cands) {
    nm <- .resolve_col(qc, cands)
    if (is.na(nm)) NULL else qc[[nm]]
  }

  ## A96-style well: letter is the row, digits the column.
  wr <- wc <- NULL
  well <- col(c("Well", "Sample_Well", "Well_Position", "WellPosition",
                "Sentrix_Position"))
  if (!is.null(well)) {
    w <- toupper(trimws(as.character(well)))
    hit <- grepl("^[A-P]0?[0-9]{1,2}$", w)
    if (any(hit, na.rm = TRUE)) {
      wr <- ifelse(hit, sub("^([A-P]).*$", "\\1", w), NA_character_)
      wc <- ifelse(hit, sub("^[A-P]0?([0-9]{1,2})$", "\\1", w), NA_character_)
    }
  }

  out <- list(
    slide      = qc$sentrix_slide %||% col(c("Slide", "Chip", "Sentrix_ID",
                                             "SentrixID", "Sentrix_Barcode")),
    slide_row  = qc$sentrix_row %||% NULL,
    slide_col  = qc$sentrix_col %||% NULL,
    plate      = col(c("Plate", "Sample_Plate", "Sample_Group", "batch_folder")),
    well_row   = wr,
    well_col   = wc,
    age        = if (!is.null(qc$reported_age) && any(is.finite(qc$reported_age)))
                   qc$reported_age else col(c(cfg$agecol, cfg$agealiases)),
    sex        = qc$reported_sex %||% col(c(cfg$sexcol, cfg$sexaliases)))

  ## Drop anything absent, constant, or entirely missing -- a panel of one
  ## level says nothing.
  keep <- vapply(out, function(v) {
    if (is.null(v)) return(FALSE)
    u <- unique(v[!is.na(v)])
    length(u) > 1L
  }, logical(1))
  out[keep]
}

## Is this variable continuous enough to deserve a scatter rather than a
## boxplot? Age is the one that matters; a numeric plate number is not.
.pc_is_continuous <- function(v)
  is.numeric(v) && length(unique(v[!is.na(v)])) > 12L

## The association statistic for one PC against one variable, as a label.
.pc_stat <- function(y, v) {
  ok <- !is.na(y) & !is.na(v)
  if (sum(ok) < 4L) return(list(value = NA_real_, label = "too few samples"))
  if (.pc_is_continuous(v)) {
    r <- suppressWarnings(stats::cor(y[ok], as.numeric(v[ok])))
    return(list(value = if (is.finite(r)) r^2 else NA_real_,
                label = sprintf("r = %.2f", r)))
  }
  g <- factor(as.character(v[ok]))
  if (length(unique(g)) < 2L) return(list(value = NA_real_, label = "one level"))
  f <- tryCatch(stats::aov(y[ok] ~ g), error = function(e) NULL)
  if (is.null(f)) return(list(value = NA_real_, label = "not estimable"))
  ss <- summary(f)[[1]][["Sum Sq"]]
  if (length(ss) < 2L || sum(ss) <= 0)
    return(list(value = NA_real_, label = "no variance"))
  p <- tryCatch(summary(f)[[1]][["Pr(>F)"]][1], error = function(e) NA_real_)
  e2 <- ss[1] / sum(ss)
  list(value = e2, label = sprintf("eta2 = %.2f%s", e2,
                                   if (is.na(p)) "" else sprintf(", p = %.2g", p)))
}

## One PC against one variable.
.pc_one_panel <- function(y, v, k, ve, varname, th) {
  st <- .pc_stat(y, v)
  ttl <- sprintf("PC%d (%.1f%%) ~ %s", k, ve, varname)
  sub <- st$label
  if (is.finite(st$value) && st$value < 0.10) sub <- paste0(sub, "  (weak)")

  if (.pc_is_continuous(v)) {
    d <- data.frame(x = as.numeric(v), y = y)
    d <- d[stats::complete.cases(d), , drop = FALSE]
    return(ggplot2::ggplot(d, ggplot2::aes(.data$x, .data$y)) +
      ggplot2::geom_point(size = 1.1, alpha = 0.85, colour = "steelblue") +
      ggplot2::geom_smooth(method = "lm", formula = y ~ x, se = FALSE,
                           linewidth = 0.4, colour = "grey40") + th +
      ggplot2::theme(plot.title = ggplot2::element_text(size = 9)) +
      ggplot2::labs(title = ttl, subtitle = sub, x = varname,
                    y = sprintf("PC%d", k)))
  }
  d <- data.frame(grp = factor(as.character(v)), y = y)
  d <- d[!is.na(d$grp) & !is.na(d$y), , drop = FALSE]
  ggplot2::ggplot(d, ggplot2::aes(.data$grp, .data$y, colour = .data$grp)) +
    ggplot2::geom_boxplot(outlier.shape = NA, colour = "grey60", fill = NA,
                          linewidth = 0.3) +
    ggplot2::geom_jitter(width = 0.18, height = 0, size = 0.9, alpha = 0.8) +
    ggplot2::guides(colour = "none") + th +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 30, hjust = 1,
                                                       size = 6),
                   plot.title = ggplot2::element_text(size = 9)) +
    ggplot2::labs(title = ttl, subtitle = sub, x = NULL,
                  y = sprintf("PC%d", k))
}

## One page: PC1..PC6 against a single variable.
.pc_page <- function(sc, v, varname, ve, th) {
  n <- min(.MQC_PC_NPC, ncol(sc))
  grobs <- lapply(seq_len(n), function(k)
    .pc_one_panel(sc[, k], v, k, ve[k], varname, th))
  gridExtra::grid.arrange(
    grobs = grobs, ncol = 3,
    top = sprintf("Principal components versus %s", varname))
  invisible(NULL)
}

## The driver: a summary page naming what each PC tracks, then one page per
## variable at six panels a page.
.p_pcvars <- function(cc, qc, th, logger, npc = .MQC_PC_NPC) {
  pc <- cc$pca
  if (is.null(pc) || is.null(pc$scores)) return(invisible(NULL))
  sc <- pc$scores
  i <- match(rownames(sc), qc$sample_id)
  qc <- qc[i, , drop = FALSE]
  ve <- (pc$sdev^2 / sum(pc$sdev^2)) * 100
  npc <- min(npc, ncol(sc))

  ## ---- the variables that always get a page ------------------------------
  req <- .pc_required_vars(qc)
  ## Two names can resolve to the same column -- "plate" and batch_folder, or
  ## sex and reported_sex -- and a second page of identical data is noise.
  seen <- character(0)
  fingerprint <- function(v) paste(as.character(v), collapse = "\r")
  req <- req[!duplicated(vapply(req, fingerprint, character(1)))]
  if (length(req)) {
    for (nm in names(req)) {
      seen <- c(seen, fingerprint(req[[nm]]))
      .pc_page(sc, req[[nm]], nm, ve, th)
    }
    logger$log("plots", sprintf(
      "PC pages for the standard variables: %s", paste(names(req), collapse = ", ")))
  }
  missing <- setdiff(c("slide", "slide_row", "slide_col", "plate",
                       "well_row", "well_col", "age", "sex"), names(req))
  if (length(missing))
    logger$log("plots", sprintf(
      "no PC page for %s: absent from the sample sheet, or constant",
      paste(missing, collapse = ", ")))

  ## ---- anything else in the sheet that actually associates ---------------
  ## Only genuine sample metadata is eligible. methylQC's own outputs are
  ## excluded: associating a component with `flagged` or `mds_outlier` is
  ## circular -- those are derived from the same beta matrix the PCA is built
  ## on -- and it crowds out the batch or tissue variable the panel exists to
  ## surface.
  drop <- c(.MQC_DERIVED_COLS, .MQC_POSITION_COLS, names(req),
            "Slide", "Chip", "Sentrix_ID", "Plate", "Well", "Sample_Well")
  meta <- qc[, setdiff(names(qc), drop), drop = FALSE]
  meta <- meta[, !grepl("^(cell_|age_|mean_|n_probes|na_intensity|inf1_|rg_)",
                        names(meta)), drop = FALSE]
  meta <- meta[, vapply(meta, function(v) length(unique(v[!is.na(v)])) > 1L,
                        logical(1)), drop = FALSE]
  ## Drop anything that repeats a page already drawn, by value not by name.
  if (ncol(meta))
    meta <- meta[, !vapply(meta, function(v) fingerprint(v) %in% seen,
                           logical(1)), drop = FALSE]
  if (!ncol(meta)) return(invisible(NULL))

  assoc <- .pcassoc(sc, meta, npc)
  if (is.null(assoc)) return(invisible(NULL))
  best <- stats::aggregate(eta2 ~ variable, data = assoc, FUN = max)
  best <- best[best$eta2 >= .MQC_PC_MINETA, , drop = FALSE]
  best <- utils::head(best[order(-best$eta2), , drop = FALSE], .MQC_PC_MAXEXTRA)
  if (!nrow(best)) {
    logger$log("plots", sprintf(
      "no further metadata variable reaches eta2 %.2f against PC1-%d",
      .MQC_PC_MINETA, npc))
    return(invisible(NULL))
  }
  for (k in seq_len(nrow(best)))
    .pc_page(sc, meta[[best$variable[k]]], best$variable[k], ve, th)
  logger$log("plots", sprintf(
    "PC pages for %d further variable(s): %s", nrow(best),
    paste(sprintf("%s(max eta2=%.2f)", best$variable, best$eta2),
          collapse = ", ")))
  invisible(NULL)
}
