## ---------------------------------------------------------------------------
## plots.R -- the QC report.
##
## FROZEN VERSUS REGENERATED
## -------------------------
## Panels are split by whether any user-tunable threshold reaches them.
##
##   Regenerated by qcplots():  call rate, intensity, probe failure, sex, age
##   Frozen after Stage 2:      PCA, MDS, beta density
##
## The PCA input probe set is defined WITHOUT reference to any tunable
## threshold (see pcainput below), so freezing it is principled rather than
## stale: re-running with a different `detp` cannot change it, and there is no
## hidden inconsistency between the PCA panel and the rest of the report.
##
## v2 computed PCA on the cleaned matrix and then took complete.cases(), which
## required a probe to have passed detection in EVERY sample. That made the
## probe set depend both on `detp` and on cohort size. Simulating a realistic
## per-probe failure distribution, the fraction of probes with zero failures
## fell from 90.5% at n = 50 to 74.7% at n = 1500, while tolerating failure in
## 1% of samples held it near 90% at every cohort size. Since cell types are
## processed into separate output directories of unequal size, the v2
## behaviour meant their PCAs were built on systematically different probe
## sets.
## ---------------------------------------------------------------------------

## Fixed parameters of the PCA input. Deliberately NOT user options.
.MQC_PCA_NTOP   <- 100000L   # top-variance probes retained
.MQC_PCA_DETP   <- 0.05      # internal detection threshold, not cfg$detp
.MQC_PCA_TOLER  <- 0.01      # allow failure in up to 1% of samples

#' Build the PCA input matrix
#'
#' Selection criteria are fixed and independent of the user's options, so that
#' the PCA is stable across re-runs and comparable across cohorts of different
#' size.
#'
#' @param betas unmasked beta matrix.
#' @param detp detection p-value matrix.
#' @param design named logical design mask.
#' @param sex_probes probe IDs on the sex chromosomes.
#' @param logger optional logger.
#' @return a numeric matrix of probes by samples, free of \code{NA}.
#' @export
#' @examples
#' \dontrun{
#' bt <- pcainput(betas, detp, design, sexprobes("EPIC"))
#' }
pcainput <- function(betas, detp = NULL, design = NULL, sex_probes = character(0),
                     logger = NULL) {
  logger <- logger %||% nulllog()

  keep <- grepl("^(cg|ch)", rownames(betas))
  if (length(sex_probes)) keep <- keep & !(rownames(betas) %in% sex_probes)
  if (!is.null(design)) {
    dm <- align_to(design, rownames(betas), "design mask", fill = TRUE)
    keep <- keep & !dm
  }
  b <- betas[keep, , drop = FALSE]
  if (!nrow(b)) return(b)

  if (!is.null(detp)) {
    d <- conform_to(detp, betas, "detP matrix")[keep, , drop = FALSE]

    ## Samples that failed outright are excluded from the denominator. One
    ## dead array makes every probe's failure rate at least 1/n, which at the
    ## fixed 1% tolerance discarded the ENTIRE probe set and silently dropped
    ## the PCA, MDS and scree panels from the report.
    dead <- colMeans(is.na(d) | d > .MQC_PCA_DETP) > 0.5
    if (any(dead) && sum(!dead) >= 3L) {
      logger$log("pca", sprintf(
        "%d sample(s) failed detection almost everywhere and are excluded from the probe-selection denominator",
        sum(dead)))
      d <- d[, !dead, drop = FALSE]
    }

    fail <- rowMeans(is.na(d) | d > .MQC_PCA_DETP)
    b <- b[fail <= .MQC_PCA_TOLER, , drop = FALSE]
  }
  if (!nrow(b)) return(b)

  ## Fill the residual handful of NAs with the probe mean. At <= 1% missing
  ## this is negligible, and it removes the complete.cases fragility.
  na_idx <- which(is.na(b), arr.ind = TRUE)
  if (nrow(na_idx)) {
    rm_ <- rowMeans(b, na.rm = TRUE)
    b[na_idx] <- rm_[na_idx[, 1]]
    b <- b[is.finite(rowMeans(b)), , drop = FALSE]
  }

  v <- .rowVars(b)
  top <- order(v, decreasing = TRUE)[seq_len(min(.MQC_PCA_NTOP, length(v)))]
  out <- b[sort(top), , drop = FALSE]
  logger$log("pca", sprintf(
    "PCA input: %s probes (cg/ch, sex and design excluded, detection failure <= %.0f%%)",
    format(nrow(out), big.mark = ","), 100 * .MQC_PCA_TOLER))
  out
}

#' Compute the frozen PCA
#'
#' @param bt output of \code{\link{pcainput}}.
#' @param logger optional logger.
#' @return a list with \code{scores}, \code{sdev} and \code{n_probes}, or
#'   \code{NULL} when there is too little data.
#' @export
#' @examples
#' \dontrun{
#' pc <- runpca(pcainput(betas, detp, design))
#' }
runpca <- function(bt, logger = NULL) {
  logger <- logger %||% nulllog()
  if (is.null(bt) || nrow(bt) < 100L || ncol(bt) < 3L) {
    logger$log("pca", "too few probes or samples for PCA")
    return(NULL)
  }
  t0 <- Sys.time()
  ## Centred but NOT scaled. Betas already share one bounded scale, so dividing
  ## each probe by its own SD gives every probe equal weight and exactly undoes
  ## the top-variance selection pcainput() just performed; it also divides
  ## near-constant probes by floating-point residue.
  p <- stats::prcomp(t(bt), center = TRUE, scale. = FALSE)
  logger$log("pca", sprintf("PCA on %s probes x %d samples in %s",
                            format(nrow(bt), big.mark = ","), ncol(bt),
                            fmtdur(as.numeric(difftime(Sys.time(), t0, units = "secs")))))
  ## `rotation` is n_probes x n_PCs and is never used by the plots; dropping
  ## it turns a 1.2 GiB object into a few megabytes.
  list(scores = p$x, sdev = p$sdev, n_probes = nrow(bt))
}

#' Multidimensional scaling coordinates
#'
#' @param bt PCA input matrix.
#' @param logger optional logger.
#' @return a two-column matrix, or \code{NULL}.
#' @keywords internal
#' @noRd
runmds <- function(bt, logger = NULL) {
  logger <- logger %||% nulllog()
  if (is.null(bt) || ncol(bt) < 3L || !nrow(bt)) return(NULL)
  ## pcainput() returns its probes in row order, not variance order, so taking
  ## the first 5,000 rows sampled one end of the manifest rather than the most
  ## informative probes. Take the 5,000 most variable instead.
  n <- min(5000L, nrow(bt))
  sub <- if (n < nrow(bt)) {
    v <- .rowVars(bt)
    bt[sort(order(v, decreasing = TRUE)[seq_len(n)]), , drop = FALSE]
  } else bt
  d <- tryCatch(stats::dist(t(sub)), error = function(e) NULL)
  if (is.null(d)) return(NULL)
  m <- tryCatch(stats::cmdscale(d, k = 2), error = function(e) NULL)
  if (is.null(m) || !is.matrix(m) || ncol(m) < 2L) return(NULL)
  if (!is.null(m)) colnames(m) <- c("MDS1", "MDS2")
  m
}

#' Per-sample beta density curves
#'
#' Cached rather than recomputed, because the density of a beta matrix does
#' not depend on any threshold.
#'
#' @param betas beta matrix.
#' @param nsub probes sampled per column.
#' @return a list with \code{x} and \code{y}.
#' @keywords internal
#' @noRd
betadensity <- function(betas, nsub = 20000L) {
  if (is.null(betas) || !ncol(betas)) return(NULL)
  ## Reproducible without stealing the caller's random stream: save and restore
  ## .Random.seed around the draw.
  old <- if (exists(".Random.seed", envir = globalenv(), inherits = FALSE))
    get(".Random.seed", envir = globalenv()) else NULL
  on.exit({
    if (is.null(old)) suppressWarnings(rm(".Random.seed", envir = globalenv()))
    else assign(".Random.seed", old, envir = globalenv())
  }, add = TRUE)
  set.seed(1L)
  idx <- if (nrow(betas) > nsub) sample.int(nrow(betas), nsub) else seq_len(nrow(betas))
  gx <- seq(0, 1, length.out = 512L)
  ys <- vapply(seq_len(ncol(betas)), function(j) {
    v <- betas[idx, j]; v <- v[is.finite(v)]
    if (length(v) < 100L) return(rep(NA_real_, length(gx)))
    stats::density(v, from = 0, to = 1, n = length(gx))$y
  }, numeric(length(gx)))
  colnames(ys) <- colnames(betas)
  list(x = gx, y = ys)
}


## ---------------------------------------------------------------------------
## The report
## ---------------------------------------------------------------------------

.theme_qc <- function() {
  ggplot2::theme_minimal(base_size = 10) +
    ggplot2::theme(
      panel.grid.minor = ggplot2::element_blank(),
      plot.title = ggplot2::element_text(face = "bold", size = 11),
      plot.subtitle = ggplot2::element_text(size = 9, colour = "grey30"))
}

#' Render the QC report
#'
#' @param qc per-sample metrics, already flagged.
#' @param cc the QC cache.
#' @param probe_fail named numeric vector of per-probe failure rates.
#' @param out destination PDF path.
#' @param failcsv destination for the failing-probe list.
#' @param pccsv destination for PC scores.
#' @param cfg options list.
#' @param logger optional logger.
#' @return \code{out}, invisibly.
#' @export
#' @examples
#' \dontrun{
#' qcreport(qc, cc, probe_fail, "qc_plots.pdf", "failed_probes.csv", "pc.csv")
#' }
qcreport <- function(qc, cc, probe_fail, out, failcsv, pccsv,
                     cfg = NULL, logger = NULL) {
  logger <- logger %||% nulllog()
  cfg <- cfg %||% mqcopts()
  th <- .theme_qc()

  dir.create(dirname(out), recursive = TRUE, showWarnings = FALSE)
  grDevices::pdf(out, width = 9, height = 6.5, onefile = TRUE)
  on.exit(grDevices::dev.off(), add = TRUE)

  .p_callrate(qc, cfg, th)
  .p_intensity(qc, cfg, th)
  .p_probefail(probe_fail, cc, cfg, th, failcsv, logger)
  .p_density(cc, th)
  .p_sex(qc, th)
  .p_age(qc, th)
  .p_mds(cc, qc, th)
  .p_pca(cc, qc, th, pccsv, logger)

  logger$log("plots", sprintf("QC report written to %s", out))
  invisible(out)
}

.p_callrate <- function(qc, cfg, th) {
  d <- qc[order(qc$call_rate), , drop = FALSE]
  d$rank <- seq_len(nrow(d))
  print(ggplot2::ggplot(d, ggplot2::aes(.data$rank, .data$call_rate)) +
    ggplot2::geom_point(ggplot2::aes(colour = .data$low_callrate), size = 1.2) +
    ggplot2::scale_colour_manual(values = c(`FALSE` = "grey40", `TRUE` = "firebrick"),
                                 name = "below threshold") +
    ggplot2::geom_hline(yintercept = cfg$samplemin, linetype = "dashed",
                        colour = "firebrick") + th +
    ggplot2::labs(
      title = "Sample call rate",
      subtitle = sprintf(
        "%d samples; %d below %.3f. Denominator is every probe on the array, so probes with a missing p-value count as failures. Detection threshold %.4g.",
        nrow(d), sum(d$low_callrate, na.rm = TRUE), cfg$samplemin, cfg$detp),
      x = "sample (ranked)", y = "call rate"))
}

.p_intensity <- function(qc, cfg, th) {
  cut <- unique(stats::na.omit(qc$intensity_cutoff))[1]
  p <- ggplot2::ggplot(qc, ggplot2::aes(.data$mean_intensity_raw)) +
    ggplot2::geom_histogram(bins = 40, fill = "steelblue", colour = "white") + th +
    ggplot2::labs(
      title = "Mean intensity (measured before dye bias and noob)",
      subtitle = sprintf(
        "Outliers flagged at %g MAD below the cohort median of log2 intensity; %d flagged. Absolute floor %.0f is a cohort-level warning only.",
        cfg$intmad, sum(qc$low_intensity, na.rm = TRUE), cfg$intfloor),
      x = "mean intensity", y = "samples")
  if (length(cut) && is.finite(cut))
    p <- p + ggplot2::geom_vline(xintercept = cut, linetype = "dashed",
                                 colour = "firebrick")
  print(p)
}

.p_probefail <- function(pf, cc, cfg, th, failcsv, logger) {
  if (is.null(pf) || !length(pf)) return(invisible(NULL))

  keep <- rep(TRUE, length(pf))
  note <- ""
  if (!isTRUE(cfg$inclqual) && !is.null(cc$design)) {
    dm <- align_to(cc$design, names(pf), "design mask", fill = FALSE)
    dm[is.na(dm)] <- FALSE
    keep <- !dm
    note <- sprintf(" %s design-masked probe(s) excluded.",
                    format(sum(dm), big.mark = ","))
  }
  v <- pf[keep]

  tail_ids <- names(v)[v >= cfg$failmin]
  write_csv_atomic(
    data.frame(probe_id = tail_ids, fail_rate = unname(v[tail_ids]),
               stringsAsFactors = FALSE), failcsv)
  logger$log("plots", sprintf("%s probe(s) at or above failmin %.3f written to %s",
                              format(length(tail_ids), big.mark = ","),
                              cfg$failmin, failcsv))

  print(ggplot2::ggplot(data.frame(f = v), ggplot2::aes(.data$f)) +
    ggplot2::geom_histogram(bins = 60, fill = "grey35", colour = "white") +
    ggplot2::scale_y_continuous(trans = "log1p") +
    ggplot2::geom_vline(xintercept = cfg$failmin, linetype = "dashed",
                        colour = "firebrick") + th +
    ggplot2::labs(
      title = "Probe failure rate across samples",
      subtitle = sprintf(
        "Detection threshold %.4g; %s probe(s) at or above failmin %.3f.%s Counts on a log scale.",
        cfg$detp, format(length(tail_ids), big.mark = ","), cfg$failmin, note),
      x = "fraction of samples in which the probe failed", y = "probes (log1p)"))
}

.p_density <- function(cc, th) {
  d <- cc$density
  if (is.null(d)) return(invisible(NULL))
  n <- ncol(d$y)
  df <- data.frame(
    x = rep(d$x, n),
    y = as.vector(d$y),
    s = rep(colnames(d$y), each = length(d$x)),
    stringsAsFactors = FALSE)
  df <- df[is.finite(df$y), , drop = FALSE]
  print(ggplot2::ggplot(df, ggplot2::aes(.data$x, .data$y, group = .data$s)) +
    ggplot2::geom_line(alpha = min(1, 15 / max(1, n)), colour = "steelblue") + th +
    ggplot2::labs(
      title = "Beta value density by sample",
      subtitle = sprintf("%d samples. Healthy arrays are bimodal with peaks near 0 and 1; a collapsed middle peak suggests a failed array.", n),
      x = "beta", y = "density"))
}

## The sex panel is the chrX/chrY intensity scatter the call is actually made
## on, so a reader can see the two clusters (or see that there is only one)
## rather than taking the classifier's word for it.
.p_sex <- function(qc, th) {
  has_int <- all(c("sex_chrX_intensity", "sex_chrY_intensity") %in% names(qc)) &&
    any(is.finite(qc$sex_chrX_intensity) & is.finite(qc$sex_chrY_intensity))
  if (!has_int) return(invisible(NULL))

  d <- qc[is.finite(qc$sex_chrX_intensity) & is.finite(qc$sex_chrY_intensity), ,
          drop = FALSE]
  if (!nrow(d)) return(invisible(NULL))
  called <- any(!is.na(d$inferred_sex))
  d$status <- ifelse(!is.na(d$sex_mismatch) & d$sex_mismatch, "mismatch",
              ifelse(is.na(d$inferred_sex), "not called",
              ifelse(is.na(d$reported_sex), "no reported sex", "concordant")))
  d$reported <- factor(ifelse(is.na(d$reported_sex), "n/a", d$reported_sex),
                       levels = c("F", "M", "n/a"))

  sub <- if (called)
    sprintf("%d mismatch(es) of %d samples; %d unclear.",
            sum(d$sex_mismatch, na.rm = TRUE), nrow(d),
            sum(d$sex_unclear, na.rm = TRUE))
  else
    paste("No sex was called: chrY intensity is not bimodal in this cohort",
          "(single-sex, too small, or too noisy). No mismatches are reported.")

  print(ggplot2::ggplot(d, ggplot2::aes(.data$sex_chrX_intensity,
                                        .data$sex_chrY_intensity)) +
    ggplot2::geom_point(ggplot2::aes(colour = .data$status,
                                     shape = .data$reported),
                        size = 2.4, alpha = 0.85) +
    ggplot2::scale_colour_manual(
      values = c(concordant = "grey40", mismatch = "firebrick",
                 `not called` = "grey75", `no reported sex` = "steelblue"),
      name = NULL) +
    ggplot2::scale_shape_manual(values = c(F = 16, M = 17, `n/a` = 1),
                                name = "reported") + th +
    ggplot2::labs(
      title = "Sex chromosome intensity",
      subtitle = sub,
      x = "median chrX (X-linked) intensity",
      y = "median chrY intensity"))
}

.p_age <- function(qc, th) {
  ## Select the predicted-age column by type, not by prefix. flagsamples()
  ## creates `age_outlier`, a logical, and adds it BEFORE predictages() assigns
  ## `age_horvath353`, so a bare grep("^age_") picked the flag first and the
  ## panel plotted TRUE/FALSE on the y axis instead of an age.
  agecol <- grep("^age_", names(qc), value = TRUE)
  agecol <- setdiff(agecol, grep("nprobes|nmodel|outlier", agecol, value = TRUE))
  agecol <- agecol[vapply(agecol, function(k) is.numeric(qc[[k]]), logical(1))]
  if (!length(agecol) || all(is.na(qc$reported_age))) return(invisible(NULL))
  ac <- agecol[1]
  d <- qc[is.finite(qc$reported_age) & is.finite(qc[[ac]]), , drop = FALSE]
  if (!nrow(d)) return(invisible(NULL))
  r <- suppressWarnings(stats::cor(d$reported_age, d[[ac]], use = "complete.obs"))
  print(ggplot2::ggplot(d, ggplot2::aes(.data$reported_age, .data[[ac]])) +
    ggplot2::geom_abline(slope = 1, intercept = 0, colour = "grey70") +
    ggplot2::geom_point(ggplot2::aes(colour = .data$age_outlier), size = 1.4) +
    ggplot2::scale_colour_manual(values = c(`FALSE` = "grey30", `TRUE` = "firebrick"),
                                 name = "cohort age outlier") + th +
    ggplot2::labs(
      title = "Reported age versus epigenetic age",
      subtitle = sprintf("n = %d, Pearson r = %.3f. No mask is applied before age prediction.",
                         nrow(d), r),
      x = "reported age (years)", y = ac))
}

.p_mds <- function(cc, qc, th) {
  m <- cc$mds
  if (is.null(m)) return(invisible(NULL))
  d <- as.data.frame(m); d$sample_id <- rownames(m)
  d$flagged <- qc$flagged[match(d$sample_id, qc$sample_id)]
  print(ggplot2::ggplot(d, ggplot2::aes(.data$MDS1, .data$MDS2)) +
    ggplot2::geom_point(ggplot2::aes(colour = .data$flagged), size = 1.5) +
    ggplot2::scale_colour_manual(values = c(`FALSE` = "grey40", `TRUE` = "firebrick"),
                                 name = "flagged", na.value = "grey75") + th +
    ggplot2::labs(title = "MDS of retained probes",
                  subtitle = "Frozen after Stage 2; independent of the detection threshold."))
}

.p_pca <- function(cc, qc, th, pccsv, logger) {
  pc <- cc$pca
  if (is.null(pc) || is.null(pc$scores)) return(invisible(NULL))
  sc <- as.data.frame(pc$scores)
  sc$sample_id <- rownames(pc$scores)
  write_csv_atomic(sc, pccsv)

  ve <- (pc$sdev^2 / sum(pc$sdev^2)) * 100
  ns <- min(20L, length(ve))
  print(ggplot2::ggplot(
      data.frame(PC = factor(paste0("PC", seq_len(ns)),
                             levels = paste0("PC", seq_len(ns))),
                 v = ve[seq_len(ns)]),
      ggplot2::aes(.data$PC, .data$v)) +
    ggplot2::geom_col(fill = "steelblue") + th +
    ggplot2::labs(
      title = "Scree plot",
      subtitle = sprintf(
        "Top %d of %d PCs, %d samples, %s probes. Input: cg/ch only, sex chromosomes and design-masked probes excluded, detection failure in at most 1%% of samples at a fixed internal threshold of %.2f. Independent of the user detection threshold.",
        ns, length(ve), nrow(sc), format(pc$n_probes, big.mark = ","),
        .MQC_PCA_DETP),
      x = NULL, y = "% variance explained"))

  d <- sc
  d$flagged <- qc$flagged[match(d$sample_id, qc$sample_id)]
  if (all(c("PC1", "PC2") %in% names(d))) {
    print(ggplot2::ggplot(d, ggplot2::aes(.data$PC1, .data$PC2)) +
      ggplot2::geom_point(ggplot2::aes(colour = .data$flagged), size = 1.5) +
      ggplot2::scale_colour_manual(values = c(`FALSE` = "grey40", `TRUE` = "firebrick"),
                                   name = "flagged", na.value = "grey75") + th +
      ggplot2::labs(
        title = "PC1 versus PC2",
        subtitle = sprintf("%.1f%% and %.1f%% of variance.", ve[1], ve[2])))
  }
  logger$log("plots", sprintf("PC scores written to %s", pccsv))
}
