## ---------------------------------------------------------------------------
## plots.R -- the QC report.
##
## Goal:    one multi-page PDF that shows, per sample, what is wrong and why.
## Approach: every per-sample panel carries the SAME flag colouring, so a
##          sample flagged on the call-rate panel is identifiable on the
##          intensity, density, sex, age, MDS and PCA panels too. Panels split
##          by whether a user-tunable threshold reaches them.
## Inputs:  the flagged metrics frame and the QC cache.
## Outputs: qc_plots.pdf, failed_probes.csv, pc_scores.csv.
## Usage:   qcreport(flags, cc, probe_fail, out, failcsv, pccsv)
##
## FROZEN VERSUS REGENERATED
## -------------------------
##   Regenerated by qcplots():  call rate, intensity, probe failure, density,
##                              sex, age, MDS, and the PC/metadata panels
##   Frozen after Stage 2:      the PCA and MDS coordinates themselves
##
## Everything except the coordinates is recomputed from qccache.rds, so a
## threshold change re-renders the whole report in about a second and never
## opens a matrix file. The coordinates are frozen legitimately rather than
## merely reused: pcainput() defines its probe set without reference to any
## user-tunable threshold, so re-running with a different `detp` could not
## change them.
## ---------------------------------------------------------------------------

## Fixed parameters of the PCA input. Deliberately NOT user options.
.MQC_PCA_NTOP   <- 100000L   # top-variance probes retained
.MQC_PCA_DETP   <- 0.05      # internal detection threshold, not cfg$detp
.MQC_PCA_TOLER  <- 0.01      # allow failure in up to 1% of samples

## Probes carried into the MDS distance, from the PCA input.
.MQC_MDS_NTOP   <- 5000L

## The expanded PC/metadata pages: minimum association worth a panel, panels
## per page, and a cap so a sheet with many columns cannot bloat the report.
.MQC_PC_MINETA    <- 0.10
.MQC_PC_PERPAGE   <- 8L
.MQC_PC_MAXPANELS <- 24L

## Columns methylQC itself produces. Excluded from the PC/metadata panel so a
## component cannot be "explained" by a flag derived from the same matrix.
.MQC_DERIVED_COLS <- c(
  "sample_id", "Basename", "sentrix", "flagcat", "flag_reason", "flagged",
  "low_callrate", "low_intensity", "sex_mismatch", "sex_unknown",
  "sex_unclear", "mds_outlier", "age_outlier", "inferred_sex",
  "call_rate", "detp_threshold", "intensity_cutoff", "reported_age",
  "sex_confidence", "sex_chrX_intensity", "sex_chrY_intensity",
  "mean_intensity_raw", "mean_intensity_mu", "detected_platform")

## Chip position, parsed by discover() from the Sentrix barcode. Kept as
## candidates for the PC panels: slide, row and column are the physical
## variables most likely to carry a batch effect.
.MQC_POSITION_COLS <- c("sentrix_slide", "sentrix_row", "sentrix_col")

## One palette, used by every per-sample panel.
.MQC_FLAG_COLS <- c(
  "pass"                = "grey55",
  "low call rate"       = "firebrick",
  "low intensity"       = "darkorange2",
  "call rate + intensity" = "purple3")

#' Categorise each sample by the two sample-level flags
#'
#' The call-rate and intensity flags are the two that every other panel carries
#' through, so they are turned into one factor here and reused everywhere.
#'
#' @param qc flagged metrics frame.
#' @return a factor with the levels of \code{.MQC_FLAG_COLS}.
#' @keywords internal
#' @noRd
.flagcat <- function(qc) {
  cr <- isTRUE_vec(qc$low_callrate)
  it <- isTRUE_vec(qc$low_intensity)
  factor(ifelse(cr & it, "call rate + intensity",
         ifelse(cr, "low call rate",
         ifelse(it, "low intensity", "pass"))),
         levels = names(.MQC_FLAG_COLS))
}

## NA-safe logical coercion; a flag that could not be computed is not a flag.
#' @keywords internal
#' @noRd
isTRUE_vec <- function(x) {
  if (is.null(x)) return(logical(0))
  x <- as.logical(x)
  x[is.na(x)] <- FALSE
  x
}

.scale_flag <- function(name = "sample flag")
  ggplot2::scale_colour_manual(values = .MQC_FLAG_COLS, name = name,
                               drop = FALSE, na.value = "grey80")

#' Build the PCA input matrix
#'
#' Selection criteria are fixed and independent of the user's options, so that
#' the PCA is stable across re-runs and comparable across cohorts of different
#' size.
#'
#' @param betas unmasked beta matrix.
#' @param detp detection p-value matrix.
#' @param design named logical design mask.
#' @param sex_probes probe IDs on the sex chromosomes.
#' @param logger optional logger.
#' @return a numeric matrix of probes by samples, free of \code{NA}.
#' @export
#' @examples
#' \dontrun{
#' bt <- pcainput(betas, detp, design, sexprobes("EPIC"))
#' }
pcainput <- function(betas, detp = NULL, design = NULL, sex_probes = character(0),
                     logger = NULL) {
  logger <- logger %||% nulllog()

  keep <- grepl("^(cg|ch)", rownames(betas))
  if (length(sex_probes)) keep <- keep & !(rownames(betas) %in% sex_probes)
  if (!is.null(design)) {
    dm <- align_to(design, rownames(betas), "design mask", fill = TRUE)
    keep <- keep & !dm
  }
  b <- betas[keep, , drop = FALSE]
  if (!nrow(b)) return(b)

  if (!is.null(detp)) {
    d <- conform_to(detp, betas, "detP matrix")[keep, , drop = FALSE]

    ## Samples that failed outright are excluded from the denominator. One
    ## dead array makes every probe's failure rate at least 1/n, which at the
    ## fixed 1% tolerance discarded the ENTIRE probe set and silently dropped
    ## the PCA, MDS and scree panels from the report.
    dead <- colMeans(is.na(d) | d > .MQC_PCA_DETP) > 0.5
    if (any(dead) && sum(!dead) >= 3L) {
      logger$log("pca", sprintf(
        "%d sample(s) failed detection almost everywhere and are excluded from the probe-selection denominator",
        sum(dead)))
      d <- d[, !dead, drop = FALSE]
    }

    fail <- rowMeans(is.na(d) | d > .MQC_PCA_DETP)
    b <- b[fail <= .MQC_PCA_TOLER, , drop = FALSE]
  }
  if (!nrow(b)) return(b)

  ## Fill the residual handful of NAs with the probe mean. At <= 1% missing
  ## this is negligible, and it removes the complete.cases fragility.
  na_idx <- which(is.na(b), arr.ind = TRUE)
  if (nrow(na_idx)) {
    rm_ <- rowMeans(b, na.rm = TRUE)
    b[na_idx] <- rm_[na_idx[, 1]]
    b <- b[is.finite(rowMeans(b)), , drop = FALSE]
  }

  v <- .rowVars(b)
  top <- order(v, decreasing = TRUE)[seq_len(min(.MQC_PCA_NTOP, length(v)))]
  out <- b[sort(top), , drop = FALSE]
  logger$log("pca", sprintf(
    "PCA input: %s probes (cg/ch, sex and design excluded, detection failure <= %.0f%%)",
    format(nrow(out), big.mark = ","), 100 * .MQC_PCA_TOLER))
  out
}

## The sentence that describes what pcainput() kept, reused by both the MDS and
## the PCA panels so the reader never has to guess what "retained" means.
.retained_text <- function(n_probes = NA) {
  sprintf(paste("Retained probes = cg/ch probes only, excluding sex chromosomes",
                "and design-masked probes, and requiring detection failure in",
                "at most %.0f%% of samples at a fixed internal p of %.2f;",
                "residual gaps filled with the probe mean, then the %s most",
                "variable kept%s."),
          100 * .MQC_PCA_TOLER, .MQC_PCA_DETP,
          format(.MQC_PCA_NTOP, big.mark = ","),
          if (is.na(n_probes)) "" else
            sprintf(" (%s entered)", format(n_probes, big.mark = ",")))
}

#' Compute the frozen PCA
#'
#' @param bt output of \code{\link{pcainput}}.
#' @param logger optional logger.
#' @return a list with \code{scores}, \code{sdev} and \code{n_probes}, or
#'   \code{NULL} when there is too little data.
#' @export
#' @examples
#' \dontrun{
#' pc <- runpca(pcainput(betas, detp, design))
#' }
runpca <- function(bt, logger = NULL) {
  logger <- logger %||% nulllog()
  if (is.null(bt) || nrow(bt) < 100L || ncol(bt) < 3L) {
    logger$log("pca", "too few probes or samples for PCA")
    return(NULL)
  }
  t0 <- Sys.time()
  ## Centred but NOT scaled. Betas already share one bounded scale, so dividing
  ## each probe by its own SD gives every probe equal weight and exactly undoes
  ## the top-variance selection pcainput() just performed; it also divides
  ## near-constant probes by floating-point residue.
  p <- stats::prcomp(t(bt), center = TRUE, scale. = FALSE)
  logger$log("pca", sprintf("PCA on %s probes x %d samples in %s",
                            format(nrow(bt), big.mark = ","), ncol(bt),
                            fmtdur(as.numeric(difftime(Sys.time(), t0, units = "secs")))))
  ## `rotation` is n_probes x n_PCs and is never used by the plots; dropping
  ## it turns a 1.2 GiB object into a few megabytes.
  list(scores = p$x, sdev = p$sdev, n_probes = nrow(bt))
}

#' Multidimensional scaling coordinates
#'
#' @param bt PCA input matrix.
#' @param logger optional logger.
#' @return a two-column matrix, or \code{NULL}.
#' @keywords internal
#' @noRd
runmds <- function(bt, logger = NULL) {
  logger <- logger %||% nulllog()
  if (is.null(bt) || ncol(bt) < 3L || !nrow(bt)) return(NULL)
  ## pcainput() returns its probes in row order, not variance order, so taking
  ## the first rows sampled one end of the manifest rather than the most
  ## informative probes. Take the most variable instead.
  n <- min(.MQC_MDS_NTOP, nrow(bt))
  sub <- if (n < nrow(bt)) {
    v <- .rowVars(bt)
    bt[sort(order(v, decreasing = TRUE)[seq_len(n)]), , drop = FALSE]
  } else bt
  d <- tryCatch(stats::dist(t(sub)), error = function(e) NULL)
  if (is.null(d)) return(NULL)
  m <- tryCatch(stats::cmdscale(d, k = 2), error = function(e) NULL)
  if (is.null(m) || !is.matrix(m) || ncol(m) < 2L) return(NULL)
  colnames(m) <- c("MDS1", "MDS2")
  attr(m, "n_probes") <- n
  m
}

#' Flag samples far from the cohort centroid in MDS space
#'
#' Distance is measured from the coordinate-wise median, which is unaffected by
#' the outliers it is meant to find, and scaled by the median absolute
#' deviation of those distances.
#'
#' @param mds a two-column MDS coordinate matrix.
#' @param nsd distance, in SDs, beyond which a sample is an outlier.
#' @return a named logical vector, with the radius as an attribute.
#' @export
#' @examples
#' m <- cbind(MDS1 = c(0, 0.1, -0.1, 5), MDS2 = c(0, -0.1, 0.1, 5))
#' rownames(m) <- paste0("s", 1:4)
#' mdsoutlier(m)
mdsoutlier <- function(mds, nsd = NULL) {
  nsd <- .opt(nsd, "mdssd")
  if (is.null(mds) || !is.matrix(mds) || nrow(mds) < 4L) return(NULL)
  centre <- apply(mds, 2L, stats::median, na.rm = TRUE)
  d <- sqrt(rowSums(sweep(mds, 2L, centre)^2))
  s <- stats::mad(d)
  if (!is.finite(s) || s <= 0) s <- stats::sd(d)
  if (!is.finite(s) || s <= 0) return(NULL)
  r <- stats::median(d) + nsd * s
  out <- stats::setNames(d > r, rownames(mds))
  attr(out, "radius") <- r
  attr(out, "centre") <- centre
  attr(out, "dist") <- d
  out
}

#' Per-sample beta density curves
#'
#' Cached rather than recomputed, because the density of a beta matrix does
#' not depend on any threshold.
#'
#' @param betas beta matrix.
#' @param nsub probes sampled per column.
#' @return a list with \code{x} and \code{y}.
#' @keywords internal
#' @noRd
betadensity <- function(betas, nsub = 20000L) {
  if (is.null(betas) || !ncol(betas)) return(NULL)
  ## Reproducible without stealing the caller's random stream: save and restore
  ## .Random.seed around the draw.
  old <- if (exists(".Random.seed", envir = globalenv(), inherits = FALSE))
    get(".Random.seed", envir = globalenv()) else NULL
  on.exit({
    if (is.null(old)) suppressWarnings(rm(".Random.seed", envir = globalenv()))
    else assign(".Random.seed", old, envir = globalenv())
  }, add = TRUE)
  set.seed(1L)
  idx <- if (nrow(betas) > nsub) sample.int(nrow(betas), nsub) else seq_len(nrow(betas))
  gx <- seq(0, 1, length.out = 512L)
  ys <- vapply(seq_len(ncol(betas)), function(j) {
    v <- betas[idx, j]; v <- v[is.finite(v)]
    if (length(v) < 100L) return(rep(NA_real_, length(gx)))
    stats::density(v, from = 0, to = 1, n = length(gx))$y
  }, numeric(length(gx)))
  colnames(ys) <- colnames(betas)
  list(x = gx, y = ys)
}


## ---------------------------------------------------------------------------
## The report
## ---------------------------------------------------------------------------

.theme_qc <- function() {
  ggplot2::theme_minimal(base_size = 10) +
    ggplot2::theme(
      panel.grid.minor = ggplot2::element_blank(),
      plot.title = ggplot2::element_text(face = "bold", size = 11),
      plot.subtitle = ggplot2::element_text(size = 9, colour = "grey30"))
}

#' Render the QC report
#'
#' @param qc per-sample metrics, already flagged.
#' @param cc the QC cache.
#' @param probe_fail named numeric vector of per-probe failure rates.
#' @param out destination PDF path.
#' @param failcsv destination for the failing-probe list.
#' @param pccsv destination for PC scores.
#' @param cfg options list.
#' @param logger optional logger.
#' @return \code{out}, invisibly.
#' @export
#' @examples
#' \dontrun{
#' qcreport(qc, cc, probe_fail, "qc_plots.pdf", "failed_probes.csv", "pc.csv")
#' }
qcreport <- function(qc, cc, probe_fail, out, failcsv, pccsv,
                     cfg = NULL, logger = NULL) {
  logger <- logger %||% nulllog()
  cfg <- cfg %||% mqcopts()
  th <- .theme_qc()
  qc$flagcat <- .flagcat(qc)

  dir.create(dirname(out), recursive = TRUE, showWarnings = FALSE)
  grDevices::pdf(out, width = 9, height = 6.5, onefile = TRUE)
  on.exit(grDevices::dev.off(), add = TRUE)

  .p_callrate(qc, cfg, th)
  .p_intensity(qc, cfg, th)
  .p_probefail(qc, cfg, th)
  .p_density(cc, qc, th)
  .p_sex(qc, cc, th)
  .p_age(qc, th)
  .p_mds(cc, qc, cfg, th)
  .p_pca(cc, qc, th, pccsv, logger)
  .p_pcvars(cc, qc, th, logger)

  ## The per-probe list is still written from the per-probe rates, even though
  ## the panel is now per-sample: it is the only place probe-level failure is
  ## reported, and downstream exclusion work needs it.
  .write_failed_probes(probe_fail, cc, cfg, failcsv, logger)

  logger$log("plots", sprintf("QC report written to %s", out))
  invisible(out)
}

.p_callrate <- function(qc, cfg, th) {
  d <- qc[order(qc$call_rate), , drop = FALSE]
  d$rank <- seq_len(nrow(d))
  print(ggplot2::ggplot(d, ggplot2::aes(.data$rank, .data$call_rate)) +
    ggplot2::geom_point(ggplot2::aes(colour = .data$flagcat), size = 1.5) +
    .scale_flag() +
    ggplot2::geom_hline(yintercept = cfg$samplemin, linetype = "dashed",
                        colour = "firebrick") + th +
    ggplot2::labs(
      title = "Sample call rate",
      subtitle = sprintf(
        "%d samples; %d below %.3f. Denominator is every probe on the array, so probes with a missing p-value count as failures. Detection threshold %.4g.",
        nrow(d), sum(isTRUE_vec(d$low_callrate)), cfg$samplemin, cfg$detp),
      x = "sample (ranked by call rate)", y = "call rate"))
}

## Ranked per-sample scatter rather than a histogram, so that the samples
## flagged on the call-rate panel can be identified here too.
.p_intensity <- function(qc, cfg, th) {
  d <- qc[order(qc$mean_intensity_raw), , drop = FALSE]
  d$rank <- seq_len(nrow(d))
  cut <- unique(stats::na.omit(qc$intensity_cutoff))[1]
  p <- ggplot2::ggplot(d, ggplot2::aes(.data$rank, .data$mean_intensity_raw)) +
    ggplot2::geom_point(ggplot2::aes(colour = .data$flagcat), size = 1.5) +
    .scale_flag() + th +
    ggplot2::labs(
      title = "Mean intensity (measured before dye bias and noob)",
      subtitle = sprintf(
        "Outliers flagged at %g MAD below the cohort median of log2 intensity; %d flagged. Absolute floor %s is a cohort-level warning only. Colour also carries the call-rate flag.",
        cfg$intmad, sum(isTRUE_vec(d$low_intensity)),
        if (is.na(cfg$intfloor)) "disabled" else sprintf("%.0f", cfg$intfloor)),
      x = "sample (ranked by mean intensity)", y = "mean intensity")
  if (length(cut) && is.finite(cut))
    p <- p + ggplot2::geom_hline(yintercept = cut, linetype = "dashed",
                                 colour = "firebrick")
  print(p)
}

## Per-sample probe failure: the fraction of the array that failed detection in
## each sample, ranked, against a horizontal cut-off.
.p_probefail <- function(qc, cfg, th) {
  d <- qc
  d$pct_failed <- 100 * (1 - d$call_rate)
  d <- d[order(d$pct_failed), , drop = FALSE]
  d$rank <- seq_len(nrow(d))
  lim <- 100 * cfg$failmin
  over <- sum(d$pct_failed >= lim, na.rm = TRUE)
  print(ggplot2::ggplot(d, ggplot2::aes(.data$rank, .data$pct_failed)) +
    ggplot2::geom_point(ggplot2::aes(colour = .data$flagcat), size = 1.5) +
    .scale_flag() +
    ggplot2::geom_hline(yintercept = lim, linetype = "dashed",
                        colour = "firebrick") + th +
    ggplot2::labs(
      title = "Probe failure rate across samples",
      subtitle = sprintf(
        "Percentage of all probes on the array failing detection at p > %.4g, per sample; %d sample(s) at or above %.0f%%. Probe-level failure rates are written to failed_probes.csv.",
        cfg$detp, over, lim),
      x = "sample (ranked by % probes failed)", y = "% of probes failed"))
}

.write_failed_probes <- function(pf, cc, cfg, failcsv, logger) {
  if (is.null(pf) || !length(pf)) return(invisible(NULL))
  keep <- rep(TRUE, length(pf))
  if (!isTRUE(cfg$inclqual) && !is.null(cc$design)) {
    dm <- align_to(cc$design, names(pf), "design mask", fill = FALSE)
    dm[is.na(dm)] <- FALSE
    keep <- !dm
  }
  v <- pf[keep]
  ids <- names(v)[v >= cfg$failmin]
  write_csv_atomic(
    data.frame(probe_id = ids, fail_rate = unname(v[ids]),
               stringsAsFactors = FALSE), failcsv)
  logger$log("plots", sprintf("%s probe(s) at or above failmin %.3f written to %s",
                              format(length(ids), big.mark = ","),
                              cfg$failmin, failcsv))
}

.p_density <- function(cc, qc, th) {
  d <- cc$density
  if (is.null(d)) return(invisible(NULL))
  n <- ncol(d$y)
  cat_by_id <- stats::setNames(as.character(qc$flagcat), qc$sample_id)
  df <- data.frame(
    x = rep(d$x, n),
    y = as.vector(d$y),
    s = rep(colnames(d$y), each = length(d$x)),
    stringsAsFactors = FALSE)
  df$flagcat <- factor(unname(cat_by_id[df$s]), levels = names(.MQC_FLAG_COLS))
  df$flagcat[is.na(df$flagcat)] <- "pass"
  df <- df[is.finite(df$y), , drop = FALSE]
  ## Flagged curves drawn last and opaque so they are visible over the cohort.
  df$flagged <- df$flagcat != "pass"
  df <- df[order(df$flagged), , drop = FALSE]
  nflag <- length(unique(df$s[df$flagged]))
  print(ggplot2::ggplot(df, ggplot2::aes(.data$x, .data$y, group = .data$s,
                                         colour = .data$flagcat)) +
    ggplot2::geom_line(ggplot2::aes(alpha = .data$flagged), linewidth = 0.4) +
    .scale_flag() +
    ggplot2::scale_alpha_manual(values = c(`FALSE` = min(1, 15 / max(1, n)),
                                           `TRUE` = 1), guide = "none") + th +
    ggplot2::labs(
      title = "Beta value density by sample",
      subtitle = sprintf("%d samples, %d flagged. Healthy arrays are bimodal with peaks near 0 and 1; a collapsed middle peak suggests a failed array.",
                         n, nflag),
      x = "beta", y = "density"))
}

## chrX against chrY, coloured by REPORTED sex, with the strict cut-off drawn
## and the call-rate/intensity failures ringed.
.p_sex <- function(qc, cc, th) {
  has_int <- all(c("sex_chrX_intensity", "sex_chrY_intensity") %in% names(qc)) &&
    any(is.finite(qc$sex_chrX_intensity) & is.finite(qc$sex_chrY_intensity))
  if (!has_int) return(invisible(NULL))

  d <- qc[is.finite(qc$sex_chrX_intensity) & is.finite(qc$sex_chrY_intensity), ,
          drop = FALSE]
  if (!nrow(d)) return(invisible(NULL))
  d$reported <- factor(ifelse(is.na(d$reported_sex), "not reported", d$reported_sex),
                       levels = c("F", "M", "not reported"))
  d$qcfail <- d$flagcat != "pass"
  cut <- attr(cc, "sex_threshold") %||% cc$sex_threshold
  called <- any(!is.na(d$inferred_sex))

  p <- ggplot2::ggplot(d, ggplot2::aes(.data$sex_chrX_intensity,
                                       .data$sex_chrY_intensity))
  ## Ring the QC failures first, so the ring sits under the point.
  if (any(d$qcfail))
    p <- p + ggplot2::geom_point(
      data = d[d$qcfail, , drop = FALSE], shape = 21, size = 4.2,
      colour = "grey20", fill = NA, stroke = 0.7)
  p <- p +
    ggplot2::geom_point(ggplot2::aes(colour = .data$reported), size = 2.2) +
    ggplot2::scale_colour_manual(
      values = c(F = "#C0392B", M = "#2E70B8", `not reported` = "grey60"),
      name = "reported sex", drop = FALSE)
  if (!is.null(cut) && is.finite(cut))
    p <- p + ggplot2::geom_hline(yintercept = cut, linetype = "dashed",
                                 colour = "grey25")

  sub <- if (called)
    sprintf(paste("Strict cut-off %s: the natural break locates the two clusters,",
                  "then the cut-off is set %g MADs above the median of the LOW",
                  "chrY cluster, whose spread is pure background. Ringed points",
                  "failed call rate or intensity."),
            if (is.null(cut) || !is.finite(cut)) "" else sprintf("at %.0f", cut),
            mqcopts()$sexcutsd)
  else
    paste("No sex was called: chrY intensity is not bimodal in this cohort",
          "(single-sex, too small, or too noisy). Ringed points failed call",
          "rate or intensity.")

  print(p + th + ggplot2::labs(
    title = "Sex chromosome intensity",
    subtitle = sub,
    x = "median chrX (X-linked) intensity",
    y = "median chrY intensity"))
}

## Reported against predicted age, with a transparent +/- 3 SD band around the
## fitted line.
.p_age <- function(qc, th, nsd = 3) {
  ## Select the predicted-age column by type, not by prefix. flagsamples()
  ## creates `age_outlier`, a logical, and adds it BEFORE predictages() assigns
  ## `age_horvath353`, so a bare grep("^age_") picked the flag first and the
  ## panel plotted TRUE/FALSE on the y axis instead of an age.
  agecol <- grep("^age_", names(qc), value = TRUE)
  agecol <- setdiff(agecol, grep("nprobes|nmodel|outlier", agecol, value = TRUE))
  agecol <- agecol[vapply(agecol, function(k) is.numeric(qc[[k]]), logical(1))]
  if (!length(agecol) || !"reported_age" %in% names(qc) ||
      all(is.na(qc$reported_age))) return(invisible(NULL))
  ac <- agecol[1]
  d <- qc[is.finite(qc$reported_age) & is.finite(qc[[ac]]), , drop = FALSE]
  if (nrow(d) < 3L) return(invisible(NULL))
  d$pred <- d[[ac]]

  r <- suppressWarnings(stats::cor(d$reported_age, d$pred, use = "complete.obs"))
  fit <- stats::lm(pred ~ reported_age, data = d)
  s <- stats::sd(stats::residuals(fit))
  gx <- seq(min(d$reported_age), max(d$reported_age), length.out = 100)
  band <- data.frame(reported_age = gx,
                     fit = stats::predict(fit, data.frame(reported_age = gx)))
  band$lo <- band$fit - nsd * s
  band$hi <- band$fit + nsd * s
  outside <- sum(abs(stats::residuals(fit)) > nsd * s)

  print(ggplot2::ggplot(d, ggplot2::aes(.data$reported_age, .data$pred)) +
    ggplot2::geom_ribbon(data = band,
                         ggplot2::aes(x = .data$reported_age, ymin = .data$lo,
                                      ymax = .data$hi),
                         inherit.aes = FALSE, fill = "steelblue", alpha = 0.15) +
    ggplot2::geom_line(data = band,
                       ggplot2::aes(.data$reported_age, .data$fit),
                       inherit.aes = FALSE, colour = "steelblue") +
    ggplot2::geom_abline(slope = 1, intercept = 0, colour = "grey75",
                         linetype = "dotted") +
    ggplot2::geom_point(ggplot2::aes(colour = .data$flagcat), size = 1.8) +
    .scale_flag() + th +
    ggplot2::labs(
      title = "Reported age versus epigenetic age",
      subtitle = sprintf(
        "n = %d, Pearson r = %.3f. Band is +/- %g SD of the residuals about the fitted line (%d sample(s) outside); dotted line is y = x. No mask is applied before prediction.",
        nrow(d), r, nsd, outside),
      x = "reported age (years)", y = ac))
}

.p_mds <- function(cc, qc, cfg, th) {
  m <- cc$mds
  if (is.null(m)) return(invisible(NULL))
  d <- as.data.frame(m); d$sample_id <- rownames(m)
  i <- match(d$sample_id, qc$sample_id)
  d$flagcat <- qc$flagcat[i]
  d$flagcat[is.na(d$flagcat)] <- "pass"

  o <- mdsoutlier(m, cfg$mdssd)
  ring <- NULL
  if (!is.null(o)) {
    ctr <- attr(o, "centre"); rad <- attr(o, "radius")
    ang <- seq(0, 2 * pi, length.out = 200)
    ring <- data.frame(x = ctr[1] + rad * cos(ang), y = ctr[2] + rad * sin(ang))
  }

  p <- ggplot2::ggplot(d, ggplot2::aes(.data$MDS1, .data$MDS2))
  if (!is.null(ring))
    p <- p + ggplot2::geom_path(data = ring,
                                ggplot2::aes(.data$x, .data$y),
                                inherit.aes = FALSE, colour = "firebrick",
                                linetype = "dashed", linewidth = 0.4)
  print(p +
    ggplot2::geom_point(ggplot2::aes(colour = .data$flagcat), size = 1.8) +
    .scale_flag() + th +
    ggplot2::labs(
      title = "MDS of retained probes",
      subtitle = paste0(
        .retained_text(attr(m, "n_probes")), " ",
        if (is.null(o)) "" else sprintf(
          "Dashed circle is %g SD from the cohort centroid; %d sample(s) outside it.",
          cfg$mdssd, sum(o)))))
}

.p_pca <- function(cc, qc, th, pccsv, logger) {
  pc <- cc$pca
  if (is.null(pc) || is.null(pc$scores)) return(invisible(NULL))
  sc <- as.data.frame(pc$scores)
  sc$sample_id <- rownames(pc$scores)
  write_csv_atomic(sc, pccsv)

  ve <- (pc$sdev^2 / sum(pc$sdev^2)) * 100
  ns <- min(20L, length(ve))
  print(ggplot2::ggplot(
      data.frame(PC = factor(paste0("PC", seq_len(ns)),
                             levels = paste0("PC", seq_len(ns))),
                 v = ve[seq_len(ns)]),
      ggplot2::aes(.data$PC, .data$v)) +
    ggplot2::geom_col(fill = "steelblue") + th +
    ggplot2::labs(
      title = "Scree plot",
      subtitle = sprintf("Top %d of %d PCs, %d samples. %s",
                         ns, length(ve), nrow(sc), .retained_text(pc$n_probes)),
      x = NULL, y = "% variance explained"))
  logger$log("plots", sprintf("PC scores written to %s", pccsv))
}

#' Association between each PC and each categorical variable
#'
#' Eta squared from a one-way analysis of variance: the share of that PC's
#' variance explained by the grouping. Continuous variables are skipped, since
#' the point of the panel is to see which discrete factor a component tracks.
#'
#' @param scores PC score matrix.
#' @param meta data.frame of candidate variables, aligned to \code{scores}.
#' @param npc how many PCs to consider.
#' @return a data.frame of PC, variable, eta2 and p, best variable first.
#' @keywords internal
#' @noRd
.pcassoc <- function(scores, meta, npc = 6L) {
  npc <- min(npc, ncol(scores))
  usable <- vapply(meta, function(v) {
    v <- v[!is.na(v)]
    if (!length(v)) return(FALSE)
    if (is.numeric(v) && length(unique(v)) > 12L) return(FALSE)  # continuous
    nu <- length(unique(v))
    nu >= 2L && nu <= 12L && nu < length(v)
  }, logical(1))
  meta <- meta[, usable, drop = FALSE]
  if (!ncol(meta)) return(NULL)

  rows <- list()
  for (i in seq_len(npc)) {
    y <- scores[, i]
    for (k in names(meta)) {
      g <- factor(as.character(meta[[k]]))
      ok <- !is.na(y) & !is.na(g)
      if (sum(ok) < 4L || length(unique(g[ok])) < 2L) next
      f <- tryCatch(stats::aov(y[ok] ~ g[ok]), error = function(e) NULL)
      if (is.null(f)) next
      ss <- summary(f)[[1]][["Sum Sq"]]
      if (length(ss) < 2L || sum(ss) <= 0) next
      p <- tryCatch(summary(f)[[1]][["Pr(>F)"]][1], error = function(e) NA_real_)
      rows[[length(rows) + 1L]] <- data.frame(
        pc = i, variable = k, eta2 = ss[1] / sum(ss), p = p,
        stringsAsFactors = FALSE)
    }
  }
  if (!length(rows)) return(NULL)
  out <- do.call(rbind, rows)
  out[order(out$pc, -out$eta2), , drop = FALSE]
}

## One panel per PC, each coloured by the categorical variable that PC tracks
## most strongly, so the reader can see what the top components represent.
.p_pcvars <- function(cc, qc, th, logger, npc = 6L) {
  pc <- cc$pca
  if (is.null(pc) || is.null(pc$scores)) return(invisible(NULL))
  sc <- pc$scores
  i <- match(rownames(sc), qc$sample_id)

  ## Only genuine sample metadata is eligible. methylQC's own outputs are
  ## excluded: associating a component with `flagged` or `mds_outlier` is
  ## circular -- those are derived from the same beta matrix the PCA is built
  ## on -- and it crowds out the batch or tissue variable the panel exists to
  ## surface. `reported_sex` stays, because that came from the sample sheet.
  meta <- qc[i, setdiff(names(qc), .MQC_DERIVED_COLS), drop = FALSE]
  meta <- meta[, !grepl("^(cell_|age_|mean_|n_probes|na_intensity|inf1_|rg_)",
                        names(meta)), drop = FALSE]
  ## A column with one level everywhere explains nothing.
  meta <- meta[, vapply(meta, function(v) length(unique(v[!is.na(v)])) > 1L,
                        logical(1)), drop = FALSE]
  if (!ncol(meta)) {
    logger$log("plots", "no categorical metadata with which to annotate the PCs")
    return(invisible(NULL))
  }

  assoc <- .pcassoc(sc, meta, npc)
  if (is.null(assoc)) {
    logger$log("plots", "no categorical metadata with which to annotate the PCs")
    return(invisible(NULL))
  }

  ve <- (pc$sdev^2 / sum(pc$sdev^2)) * 100
  panels <- list()
  for (k in seq_len(min(npc, ncol(sc)))) {
    best <- assoc[assoc$pc == k, , drop = FALSE]
    if (!nrow(best)) next
    best <- best[1, ]
    d <- data.frame(score = sc[, k],
                    grp = factor(as.character(meta[[best$variable]])),
                    stringsAsFactors = FALSE)
    d <- d[!is.na(d$grp), , drop = FALSE]
    if (!nrow(d)) next
    panels[[length(panels) + 1L]] <-
      ggplot2::ggplot(d, ggplot2::aes(.data$grp, .data$score,
                                      colour = .data$grp)) +
      ggplot2::geom_boxplot(outlier.shape = NA, colour = "grey60",
                            fill = NA, linewidth = 0.3) +
      ggplot2::geom_jitter(width = 0.18, height = 0, size = 1.1, alpha = 0.85) +
      ggplot2::guides(colour = "none") + th +
      ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 30, hjust = 1,
                                                         size = 7)) +
      ggplot2::labs(
        title = sprintf("PC%d (%.1f%%) ~ %s", k, ve[k], best$variable),
        subtitle = sprintf("eta2 = %.2f%s%s", best$eta2,
                           if (is.na(best$p)) "" else sprintf(", p = %.2g", best$p),
                           if (best$eta2 < 0.10) "  (weak)" else ""),
        x = NULL, y = sprintf("PC%d", k))
  }
  if (length(panels))
    gridExtra::grid.arrange(
      grobs = panels, ncol = 3,
      top = "Top principal components against the metadata they track most strongly")
  logger$log("plots", sprintf(
    "PC/metadata panel: %s",
    paste(sprintf("PC%d~%s(eta2=%.2f)", assoc$pc[!duplicated(assoc$pc)],
                  assoc$variable[!duplicated(assoc$pc)],
                  assoc$eta2[!duplicated(assoc$pc)]), collapse = ", ")))

  ## ---- the rest of the metadata, strongest associations first -------------
  ## The grid above answers "what does each PC represent" by showing only the
  ## single best variable per PC, which hides every other variable in the
  ## sheet. These pages show the remaining PC/variable pairs ranked by
  ## association, eight to a page, so a batch effect sitting on PC3 alongside a
  ## stronger tissue effect is still visible.
  shown <- paste(assoc$pc[!duplicated(assoc$pc)],
                 assoc$variable[!duplicated(assoc$pc)])
  rest <- assoc[!paste(assoc$pc, assoc$variable) %in% shown &
                  is.finite(assoc$eta2) & assoc$eta2 >= .MQC_PC_MINETA, ,
                drop = FALSE]
  if (!nrow(rest)) return(invisible(NULL))
  rest <- rest[order(-rest$eta2), , drop = FALSE]
  rest <- utils::head(rest, .MQC_PC_MAXPANELS)

  pages <- split(seq_len(nrow(rest)),
                 ceiling(seq_len(nrow(rest)) / .MQC_PC_PERPAGE))
  for (pi in seq_along(pages)) {
    grobs <- lapply(pages[[pi]], function(j) {
      r <- rest[j, ]
      d <- data.frame(score = sc[, r$pc],
                      grp = factor(as.character(meta[[r$variable]])),
                      stringsAsFactors = FALSE)
      d <- d[!is.na(d$grp), , drop = FALSE]
      ggplot2::ggplot(d, ggplot2::aes(.data$grp, .data$score,
                                      colour = .data$grp)) +
        ggplot2::geom_boxplot(outlier.shape = NA, colour = "grey60",
                              fill = NA, linewidth = 0.3) +
        ggplot2::geom_jitter(width = 0.18, height = 0, size = 0.9, alpha = 0.8) +
        ggplot2::guides(colour = "none") + th +
        ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 30, hjust = 1,
                                                           size = 6),
                       plot.title = ggplot2::element_text(size = 9)) +
        ggplot2::labs(
          title = sprintf("PC%d ~ %s", r$pc, r$variable),
          subtitle = sprintf("eta2 = %.2f%s", r$eta2,
                             if (is.na(r$p)) "" else sprintf(", p = %.2g", r$p)),
          x = NULL, y = sprintf("PC%d", r$pc))
    })
    gridExtra::grid.arrange(
      grobs = grobs, ncol = 4,
      top = sprintf("PC versus metadata, remaining associations (page %d of %d)",
                    pi, length(pages)))
  }
  logger$log("plots", sprintf(
    "%d further PC/metadata association(s) at eta2 >= %.2f, over %d page(s)",
    nrow(rest), .MQC_PC_MINETA, length(pages)))
}
